const searchData = {
  hotelInfo: {
    brandInfo: { chainCode: 'EX', brandCode: 'HIEX', brandName: 'Holiday Inn Express', mnemonic: 'TAOCC' },
    location: {
      introText:
        '酒店210间时尚简约的客房均设有灵活的多功能家具。可移动桌板、干湿分离卫浴等巧思设计，为入住增加了舒适性与私密性。多个充电插口和USB接口设计也可满足多种电子设备同时充电的需求。在此你可以尽享优质睡眠、畅爽沐浴、自在办公休闲和中西式自助早餐，为你打造轻松舒适的入住体验。',
      closestCity: 'Qingdao',
      distanceToCityCenter: 23.94,
      unitOfMeasure: 'KILOMETERS',
      locationProperty: {
        historical: false,
        limitedService: true,
        fullService: false,
        spa: false,
        locationDistrictDetails: { downtown: true, shoppingDistrict: true },
        locationAreaDetails: {
          airportArea: false,
          inMountains: false,
          cityCenter: true,
          directAccessToBeach: false,
          ableToWalkToBeach: false,
          beachView: false,
          nearBeach: false,
          onBeach: false,
          oceanFront: false,
          lessThanOneAndHalfMileFromBeach: false,
        },
      },
      lengthUnitOfMeasure: 'METERS',
      locationType: 'CITY',
      directionFromCityCenter: { distance: 23.94, direction: 'S', time: '0:46' },
    },
    contact: [
      {
        faxNumber: '86-0532-80968686',
        reservationsPhoneNumber: null,
        reservationsPhoneNumberMessage: false,
        frontDeskNumber: '86-0532-89081666',
        email: 'reservation@hiexqd.com',
      },
    ],
    reviews: [
      {
        userNickName: 'qian',
        reviewText: '酒店床铺舒服，房间卫生也很干净，前台小赵服务很棒，很亲切！',
        hotelMnemonic: 'TAOCC',
        userRating: 5,
        reviewTitle: '很好',
      },
      {
        userNickName: '飞翔。。',
        reviewText:
          '第一次入住智选，房间整体很干净，早餐品种还是挺多的，客房大姐很客气 入住时前台小杨很热情，给我注册会员还打了个折 整体值得推荐',
        hotelMnemonic: 'TAOCC',
        userRating: 5,
        reviewTitle: '整体非常不错',
      },
      {
        userNickName: '小七呀呀呀',
        reviewText: '挺好                                  ！！！！！！！！！！！！！！！',
        hotelMnemonic: 'TAOCC',
        userRating: 5,
        reviewTitle: '整体入住感比较舒适         ！！！！！！！！！！！',
      },
      {
        userNickName: '彼得007',
        reviewText: '电子邮件，请将中文放在首个段落！谢谢丽丽及时联系我并帮我邮寄落在宾馆的帽子和耳机',
        hotelMnemonic: 'TAOCC',
        userRating: 5,
        reviewTitle: '舒适一流',
      },
      {
        userNickName: '隐姓埋名',
        reviewText: '非常好，我很喜欢这家酒店，给我非常好的入住体验，下次还会选择入住',
        hotelMnemonic: 'TAOCC',
        userRating: 5,
        reviewTitle: '非常好，服务好',
      },
      {
        userNickName: 'Tropicana',
        reviewText: '无论从硬件设施，还是酒店人员的服务，都非常满意。下次还会再来。',
        hotelMnemonic: 'TAOCC',
        userRating: 5,
        reviewTitle: '非常舒适的入住体验',
      },
      {
        userNickName: 'TONY',
        reviewText: '酒店位置非常好，周边餐饮有众多选择，停车也非常方便。服务人员热情专业，房间整洁安静，是值得推荐的入住酒店。',
        hotelMnemonic: 'TAOCC',
        userRating: 5,
        reviewTitle: '房间整洁，服务专业到位',
      },
      {
        userNickName: 'hzw胡',
        reviewText: '非常棒的体验，服务非常好，很温馨，非常非常非常非常非常非常非常棒，非常棒非常棒',
        hotelMnemonic: 'TAOCC',
        userRating: 5,
        reviewTitle: '服务一流',
      },
      {
        userNickName: '图图缝纫机',
        reviewText: '整体干净，房间卫生。喜欢房间的布局，客服人员服务态度好，早餐吃的满意。',
        hotelMnemonic: 'TAOCC',
        userRating: 5,
        reviewTitle: '房间干净，明亮',
      },
      {
        userNickName: 'Kevin',
        reviewText: '1、服务很周到，注重细节。如：机场接送、雨伞、赠饮、口罩等。\r\n2、房间隔音很好，睡眠质量好。',
        hotelMnemonic: 'TAOCC',
        userRating: 5,
        reviewTitle: '服务周到，舒适睡眠',
      },
    ],
    profile: {
      tmpOperatingDivision: 'GRCHINA',
      roomsIncludingSuitesCount: 210,
      languagesSpokenByStaff: { listItem: ['zh', 'en', 'ko'] },
      hotelID: 23387,
      growthHotelStatus: 'Open - Accepting Guests',
      latLong: { longitude: 120.402739, latitude: 36.304937 },
      name: '青岛天一仁和智选假日酒店',
      shortDescription:
        '酒店210间时尚简约的客房均设有灵活的多功能家具。可移动桌板、干湿分离卫浴等巧思设计，为入住增加了舒适性与私密性。多个充电插口和USB接口设计也可满足多种电子设备同时充电的需求。在此你可以尽享优质睡眠、畅爽沐浴、自在办公休闲和中西式自助早餐，为你打造轻松舒适的入住体验。',
      longDescription:
        '旖旎的海滨风光、别具特色的“万国群建筑”、鲜美的海鲜和爽口的啤酒，塑造了风姿绰约的青岛。青岛天一仁和智选假日酒店坐落于青岛，配有健身中心和共用休息室，享有市景，距离青岛市博物馆有29公里。这家住宿提供的设施包括餐厅、24小时前台、客房服务以及免费WiFi。酒店拥有家庭间。\n\n这家酒店提供自助或亚洲风味早餐。\n\n青岛天一仁和智选假日酒店提供商务中心供客人使用。\n\n这家住宿距离青岛啤酒有31公里，距离青岛登州路啤酒街有32公里。最近的机场是青岛胶东国际机场，距离青岛天一仁和智选假日酒店有28公里。',
      accommodationsOverview:
        '酒店210间时尚简约的客房均设有灵活的多功能家具。可移动桌板、干湿分离卫浴等巧思设计，为入住增加了舒适性与私密性。多个充电插口和USB接口设计也可满足多种电子设备同时充电的需求。在此你可以尽享优质睡眠、畅爽沐浴、自在办公休闲和中西式自助早餐，为你打造轻松舒适的入住体验。\n酒店的多功能共享空间——“智•空间”，在非用餐时段将为你打造灵活多变的工作和休闲模式。高速网络全面覆盖，24小时自助式便利站，方便你购买各类饮品、食品点心、生活用品和纪念品等，为你带来简单、睿智的体验。',
      timeZone: 'Asia/Shanghai',
      marketingRegion: 'Greater China',
      primaryImageUrl: {
        originalUrl: 'https://digital.ihg.com/is/image/ihg/holiday-inn-express-qingdao-6048652272-original',
        formats: [
          { aspectWidth: '16', aspectHeight: '9', url: 'https://digital.ihg.com/is/image/ihg/holiday-inn-express-qingdao-6048652272-16x9' },
          { aspectWidth: '2', aspectHeight: '1', url: 'https://digital.ihg.com/is/image/ihg/holiday-inn-express-qingdao-6048652272-2x1' },
          { aspectWidth: '16', aspectHeight: '5', url: 'https://digital.ihg.com/is/image/ihg/holiday-inn-express-qingdao-6048652272-16x5' },
          { aspectWidth: '3', aspectHeight: '2', url: 'https://digital.ihg.com/is/image/ihg/holiday-inn-express-qingdao-6048652272-3x2' },
          { aspectWidth: '1', aspectHeight: '1', url: 'https://digital.ihg.com/is/image/ihg/holiday-inn-express-qingdao-6048652272-1x1' },
          { aspectWidth: '4', aspectHeight: '3', url: 'https://digital.ihg.com/is/image/ihg/holiday-inn-express-qingdao-6048652272-4x3' },
        ],
      },
      seoCity: 'qingdao',
      preSellDate: '2019-06-10',
      entityOpenDate: '2019-06-10',
      dateOpened: '2019-06-10',
      hotelStatus: 'OPEN',
      originType: 'ND',
      independentNonIHGWebsiteURL: 'www.hiexpress.com.cn',
      ihgBusinessRewardsParticipationPeriod: { startDate: '2015-03-31' },
      receiveGMRFPs: true,
      isTestHotel: false,
      locationNumber: 19228,
      listedInHolidex: true,
      innIsAPropertyMgmtHotel: true,
      yearHotelBuilt: '2019-01-01',
      managementTypeCode: 'MCA',
      managementTypeDescription: 'Managed',
      inquiryFlag: false,
      latitude: 36.304937,
      longitude: 120.402739,
      totalReviews: 49,
      averageReview: 4.591836734693878,
      overallRatingRange: 5,
      secondaryRatings: {
        StaffService: {
          Id: 'StaffService',
          AverageRating: 4.591836734693878,
          MinLabel: null,
          ValueRange: 5,
          MaxLabel: null,
          DisplayType: 'NORMAL',
          Label: 'Staff and Service',
        },
        Value: {
          Id: 'Value',
          AverageRating: 4.489795918367347,
          MinLabel: null,
          ValueRange: 5,
          MaxLabel: null,
          DisplayType: 'NORMAL',
          Label: 'Value',
        },
        Relax: {
          Id: 'Relax',
          AverageRating: 4.527777777777778,
          MinLabel: null,
          ValueRange: 5,
          MaxLabel: null,
          DisplayType: 'NORMAL',
          Label: 'Able to Relax',
        },
        RoomComfort: {
          Id: 'RoomComfort',
          AverageRating: 4.591836734693878,
          MinLabel: null,
          ValueRange: 5,
          MaxLabel: null,
          DisplayType: 'NORMAL',
          Label: 'Room and Comfort',
        },
        Breakfast: {
          Id: 'Breakfast',
          AverageRating: 4.081081081081081,
          MinLabel: null,
          ValueRange: 5,
          MaxLabel: null,
          DisplayType: 'NORMAL',
          Label: 'Variety of Breakfast Choices',
        },
        Cleanliness: {
          Id: 'Cleanliness',
          AverageRating: 4.73469387755102,
          MinLabel: null,
          ValueRange: 5,
          MaxLabel: null,
          DisplayType: 'NORMAL',
          Label: 'Room Cleanliness',
        },
        SleepQuality: {
          Id: 'SleepQuality',
          AverageRating: 4.551020408163265,
          MinLabel: null,
          ValueRange: 5,
          MaxLabel: null,
          DisplayType: 'NORMAL',
          Label: 'Sleep Quality',
        },
      },
      vatIncluded: false,
    },
    address: {
      city: '青岛',
      country: { code: 'CN', name: '中国' },
      state: { code: 'SD' },
      zip: '266109',
      street1: '青岛市城阳区长城路197-25',
      street4: null,
      consumerFriendlyURL: 'www.hiexpress.com/qdchengyang',
    },
    media: [{ id: 'media/welcomePhotos', name: 'Welcome' }],
    policies: {
      checkinTime: '14:00:00',
      checkoutTime: '12:00:00',
      checkIn: {
        minCheckInAge: 16,
        earlyCheckInAvailable: false,
        temporaryCheckInTime: '14:00:00',
        expressCheckInAvailable: true,
        legalIdsAcceptedAtCheckIn: 'identity card , Passport',
      },
      acceptedCurrencies: [{ code: 'CNY', name: '人民币                                ', symbol: '￥' }],
      pet: {
        petsAllowed: false,
        guideDogsOrServiceAnimalsAllowed: true,
        description: '不允许携带宠物入住',
        petWalkingArea: false,
        petSittingServicesAvailable: false,
      },
      paymentMethods: {
        creditCardsAccepted: { listItem: ['AX', 'VS', 'MC'] },
        paymentMethodsAccepted: {
          listItem: ['ALIPAY', 'ALIPAY_GUARANTEE', 'ALIPAY_POST_POST', 'CASH', 'CREDIT', 'CU', 'MONEY_ORDER', 'WECHAT_PAY'],
        },
        cutOffTimeAltPayDeposit: '10:00:00',
        paymentServiceInformationRequired: false,
      },
      languagesSpokenByStaff: { listItem: ['zh', 'en', 'ko'] },
      serviceChargeDetail: { description: '服务费基于每房每晚计算。餐饮及其他消费按照总价计算。' },
      negotiatedRates: {
        offeredToContractorsOrConsultants: true,
        offeredToClientSubsidiaryEmployes: true,
        offeredToClientRetirees: false,
        offeredToClientEmployesForPersonalUse: true,
        corporateTransientHotel: true,
        meetingConventionHotel: false,
      },
      onSiteFitnessCenter: true,
      oneCarParkDailyCost: true,
      offSiteFitnessCenterIncluded: false,
      ratesLoadedInGds: true,
      taxAndFee: { vatOrGstTax: false, serviceFee: false },
      walk: {
        accommodationsAtComparableHotel: true,
        roomAndTaxAtComparableHotel: true,
        transportationAtComparableHotel: true,
        phoneCallToGuestHomeOrOffice: true,
      },
      blackOutDates: [{ startDate: '2022-10-26', endDate: '2022-10-28' }],
    },
    marketing: {
      marketingText: {
        limitedTimeFeatures: {
          limitedTimeFeature: [
            {
              headLine: '享“标准价”*基础上至少20%优惠，会员额外惠享5%折上折。开启您的梦',
              status: 'INVACTIVE',
              subHeader: '您的旅行，您做主',
              shortDescription:
                '活动期间，以“驻足此刻住享精彩”预订全球数千家 IHG® 洲际集团旗下酒店及度假村，享“标准价”*基础上至少20%优惠。成为IHG优悦会会员，以“驻足此刻住享精彩（会员专享价）”预订，额外惠享5%会员专享折上折。',
              startDateEndDate: { startDate: '2019-08-22', endDate: '2019-09-24' },
              thumnailImages: {
                originalUrl: 'https://digital.ihg.com/is/image/ihg/holiday-inn-express-qingdao-6131298782-original',
                formats: [
                  {
                    aspectWidth: '2',
                    aspectHeight: '1',
                    url: 'https://digital.ihg.com/is/image/ihg/holiday-inn-express-qingdao-6131298782-2x1',
                  },
                  {
                    aspectWidth: '16',
                    aspectHeight: '9',
                    url: 'https://digital.ihg.com/is/image/ihg/holiday-inn-express-qingdao-6131298782-16x9',
                  },
                  {
                    aspectWidth: '3',
                    aspectHeight: '2',
                    url: 'https://digital.ihg.com/is/image/ihg/holiday-inn-express-qingdao-6131298782-3x2',
                  },
                  {
                    aspectWidth: '1',
                    aspectHeight: '1',
                    url: 'https://digital.ihg.com/is/image/ihg/holiday-inn-express-qingdao-6131298782-1x1',
                  },
                  {
                    aspectWidth: '4',
                    aspectHeight: '3',
                    url: 'https://digital.ihg.com/is/image/ihg/holiday-inn-express-qingdao-6131298782-4x3',
                  },
                  {
                    aspectWidth: '16',
                    aspectHeight: '5',
                    url: 'https://digital.ihg.com/is/image/ihg/holiday-inn-express-qingdao-6131298782-16x5',
                  },
                ],
              },
              newDedicatedLandingPage: {
                longDescription:
                  '"活动期间，以“驻足此刻住享精彩”预订全球数千家 IHG® 洲际集团旗下酒店及度假村，享“标准价”*基础上至少20%优惠。成为IHG优悦会会员，以“驻足此刻住享精彩（会员专享价）”预订，额外惠享5%会员专享折上折。\n\n现在到 2019 年 9 月 24日期间预订，适用于 2020 年 3 月 31 日之前的住宿 \n\n"',
                imageOrVideo: {
                  originalUrl: 'https://digital.ihg.com/is/image/ihg/holiday-inn-express-qingdao-6131298782-original',
                  formats: [
                    {
                      aspectWidth: '2',
                      aspectHeight: '1',
                      url: 'https://digital.ihg.com/is/image/ihg/holiday-inn-express-qingdao-6131298782-2x1',
                    },
                    {
                      aspectWidth: '16',
                      aspectHeight: '9',
                      url: 'https://digital.ihg.com/is/image/ihg/holiday-inn-express-qingdao-6131298782-16x9',
                    },
                    {
                      aspectWidth: '3',
                      aspectHeight: '2',
                      url: 'https://digital.ihg.com/is/image/ihg/holiday-inn-express-qingdao-6131298782-3x2',
                    },
                    {
                      aspectWidth: '1',
                      aspectHeight: '1',
                      url: 'https://digital.ihg.com/is/image/ihg/holiday-inn-express-qingdao-6131298782-1x1',
                    },
                    {
                      aspectWidth: '4',
                      aspectHeight: '3',
                      url: 'https://digital.ihg.com/is/image/ihg/holiday-inn-express-qingdao-6131298782-4x3',
                    },
                    {
                      aspectWidth: '16',
                      aspectHeight: '5',
                      url: 'https://digital.ihg.com/is/image/ihg/holiday-inn-express-qingdao-6131298782-16x5',
                    },
                  ],
                },
                customCta: {
                  linkToUrl:
                    'https://www.ihg.com/holidayinnexpress/hotels/us/en/find-hotels/hotel/rooms?qAdlt=1&qChld=0&qRms=1&qRtP=IDAFS&qSlH=TAOCC&qAkamaiCC=US&qSrt=sBR&qBrs=re.ic.in.vn.cp.vx.hi.ex.rs.cv.sb.cw.ma.ul.ki.va&qAAR=IDAFS&qWch=0&qSmP=1&setPMCookies=true&qRad=30&qRdU=mi&srb_u=1&qErm=true&qpEsst=08-22-2019&qpEsed=03-31-2020&qpMbw=3&qMsg=Save+at+least+25%25+worldwide.',
                },
              },
            },
            {
              status: 'INVACTIVE',
              category: 'Offer or Package',
              offerOrPackageSubCategory: 'Other Offer or Package',
              startDateEndDate: { startDate: '2020-06-30', endDate: '2020-09-08' },
              thumnailImages: {
                originalUrl: 'https://digital.ihg.com/is/image/ihg/holiday-inn-express-qingdao-6541942995-original',
                formats: [
                  {
                    aspectWidth: '2',
                    aspectHeight: '1',
                    url: 'https://digital.ihg.com/is/image/ihg/holiday-inn-express-qingdao-6541942995-2x1',
                  },
                  {
                    aspectWidth: '16',
                    aspectHeight: '9',
                    url: 'https://digital.ihg.com/is/image/ihg/holiday-inn-express-qingdao-6541942995-16x9',
                  },
                  {
                    aspectWidth: '3',
                    aspectHeight: '2',
                    url: 'https://digital.ihg.com/is/image/ihg/holiday-inn-express-qingdao-6541942995-3x2',
                  },
                  {
                    aspectWidth: '1',
                    aspectHeight: '1',
                    url: 'https://digital.ihg.com/is/image/ihg/holiday-inn-express-qingdao-6541942995-1x1',
                  },
                  {
                    aspectWidth: '4',
                    aspectHeight: '3',
                    url: 'https://digital.ihg.com/is/image/ihg/holiday-inn-express-qingdao-6541942995-4x3',
                  },
                  {
                    aspectWidth: '16',
                    aspectHeight: '5',
                    url: 'https://digital.ihg.com/is/image/ihg/holiday-inn-express-qingdao-6541942995-16x5',
                  },
                ],
              },
              ctaExistingLandingPage: { ctaLandingPageUrl: 'https://www.ihg.com/content/us/en/deals/member-offers/4x2020' },
            },
          ],
        },
        inStayFeedbackSupplier: 'NONE',
        hotelStayPreferenceParticipation: true,
        corporateManaged: {
          ihgConnectLandingPageMarketingDescription:
            '我们致力于维护清洁卫生的高标准。这意味着提供干净卫生、整齐有序、维护良好、符合标准的客房。如果您在入住时发现任何疏漏之处，我们保证会予以\n纠正。',
          ihgConnectLandingPageMarketingTitle: '洲全',
          ihgConnectLandingPageLinkText: '了解详情 ',
          ihgConnectLandingPageLinkUrl: 'https://www.ihg.com/content/us/en/customer-care/travel-advisory',
        },
        croAlertDates: { startDate: '2021-01-01', endDate: '2021-03-08' },
        croAlertDescription:
          'From January 28th to March 8th \n1. Those who come to our hotel from other provinces need to provide a 7-day valid nucleic acid certificate. \n2. If you come from Beijing, Shanghai, Tianjin, Hebei, Henan, Shaanxi, Heilongjiang, Jilin, Liaoning, Inner Mongolia (11 provinces and cities), you must report and do nucleic acid in Qingdao. \n3. If the guest comes from another province and does not have a 7-day valid nucleic acid certificate, you can arrange check-in first and let the guest do it. \nFinished and show us.',
        dontGoHomeWithout:
          '青岛以海鲜和啤酒著称，这里盛产海参、海米、鱿鱼丝、鱼片、烤虾等地方土特产，品种丰富，口感鲜美。青岛啤酒选用优质大麦、大米、上等啤酒花和软硬适度、洁净甘美的崂山矿泉水为原料酿制而成，纯正地道，令人回味无穷。',
        foodAndBeverageDescription:
          '每间客房均包含丰盛美味的中西式自助早餐，特色面档提供本地招牌特色，带你开启探味之旅。\n早餐时段：6:30—10:00\n午餐和晚餐时段特别推出精致可口的商务套餐，为你用餐提供多样选择。',
        hotelTileAlwaysComplimentary: '洗衣阁，健身房',
        hotelManaged: {
          ihgConnectLandingPageMarketingTitle: 'An important update on COVID-19.',
          ihgConnectLandingPageMarketingDescription: 'An important update on COVID-19.',
        },
        hotelMajorFeature:
          '酒店210间时尚简约的客房均设有灵活的多功能家具。可移动桌板、干湿分离卫浴等巧思设计，为入住增加了舒适性与私密性。多个充电插口和USB接口设计也可满足多种电子设备同时充电的需求。在此你可以尽享优质睡眠、畅爽沐浴、自在办公休闲和中西式自助早餐，为你打造轻松舒适的入住体验。',
        mustDo:
          '青岛海鲜种类繁多，包括海参、鲍鱼、石夹红蟹、鲅鱼、大对虾等。以海味为主要原料成为青岛烹饪的一大特色。青岛名菜：油爆海螺、原壳鲍鱼、辣炒蛤蜊、大虾烧白菜、肉沫海参等等，是来青岛旅游必享用的美食。',
        mustSee:
          '酒店周边休闲购物、旅游景点众多，可轻松前往鲁邦国际风情街、万象汇购物中心、青岛奥林匹克雕塑文化园、国学公园、城阳世纪公园等地，领略青岛生动的人文风情。',
        seo: {
          seoCityName: 'qingdao',
          seoMetaDescription:
            '在 青岛天一仁和智选假日 酒店收获简单、睿智的 出行体验。我们是一家位于 青岛市城阳区政府附近 的 中端酒店，为您提供“恰如所需”的服务，房价 已含免费早餐和高速网络。欢迎点击 IHG 直销渠 道进行预订，享受优惠房价。',
          seoTitle: '位于 城阳区区政府 附近的商务酒店 青岛天一仁和 智选假日酒店',
          seoLocalGuideTitle: '青岛市城阳区政府 附近景点及周边活动 青岛天一仁和 智选假日酒店',
          seoLocalGuideDescription:
            '我们位于青岛城阳区政府的青岛天一仁和智选假日酒店提供了一个现代化的空间！与朋友、同事或自己一 起探索当地景点和餐馆 欢迎点击当地活动指南获获取更多信息',
        },
        theme: 'Business travel',
        tips: 'Fangte Playground is the largest playground in Shandong.',
        welcomeMessage:
          '旖旎的海滨风光、别具特色的“万国群建筑”、鲜美的海鲜和爽口的啤酒，塑造了风姿绰约的青岛。青岛天一仁和智选假日酒店坐落于青岛，配有健身中心和共用休息室，享有市景，距离青岛市博物馆有29公里。这家住宿提供的设施包括餐厅、24小时前台、客房服务以及免费WiFi。酒店拥有家庭间。\n\n这家酒店提供自助或亚洲风味早餐。\n\n青岛天一仁和智选假日酒店提供商务中心供客人使用。\n\n这家住宿距离青岛啤酒有31公里，距离青岛登州路啤酒街有32公里。最近的机场是青岛胶东国际机场，距离青岛天一仁和智选假日酒店有28公里。',
        whatsNew: 'In Chengyang, there is Century Park, Guoxue Park, Fangte Playground.',
        specialAnnouncementDetails: [
          {
            description: '青岛天一仁和智选假日酒店现已开业！ \n预付价享受最优弹性房价9折特惠每晚每间。',
            announcementDates: { startDate: '2019-01-16', endDate: '2019-07-13' },
          },
        ],
      },
      concierge: { conciergeOnProperty: true },
      facilityNumber: 19228,
      managementType: 4,
      marketingTier: 'MFB',
      eventsAndConcierge: {
        concierge: {
          conciergeOnProperty: true,
          conciergePhoneNumber: { countryCode: '86', areaCode: '0532', phoneNumber: '89081666' },
          conciergeEmailAddress: 'jim.jiang@ihg.com',
        },
      },
    },
    facilities: [
      { id: 'BREAKFAST_INCLUDED', name: '免费早餐' },
      { id: 'WIRELESS_INTERNET', name: '无线互联网' },
      { id: 'KIDS_EAT_FREE', name: '儿童餐饮欢乐尽享' },
      { id: 'NO_PETS_ALLOWED', name: '不允许携带宠物' },
      { id: 'HEALTH_FITNESS_CENTER', name: '健身中心' },
    ],
    tax: {
      details: { vatOrGstTax: { fee: 6.6, basis: 'P' } },
      total: {
        items: [
          {
            startAndEndDate: { startDate: '2019-01-16', endDate: '2119-12-31' },
            amount: { fee: 6.6, basis: 'P' },
            information: 'PER NIGHT',
            includedInRate: false,
            description: 'ALL ROOM RATE AND SERVICE CHARGE SUBJECT 6 PCT VAT.',
            sendToIhgRfp: true,
          },
        ],
      },
      individual: {
        items: [
          {
            type: 'VAT/GST TAX',
            amount: { fee: 6.6, basis: 'P' },
            startAndEndDate: { startDate: '2019-01-16', endDate: '2119-12-31' },
            information: 'PER NIGHT',
            includedInRate: false,
            description: 'ALL ROOM RATE AND SERVICE CHARGE SUBJECT 6 PCT VAT.',
            sendToIhgRfp: true,
          },
        ],
      },
      serviceCharge: {
        startAndEndDate: { startDate: '2019-01-16', endDate: '2129-12-31' },
        information: 'NOT INCLUDED IN RATE',
        details: 'PER NIGHT',
        percentage: '10',
        description: '服务费基于每房每晚计算。餐饮及其他消费按照总价计算。',
        descriptionHolidexPlusOrGrs: 'SVC CHARGE FOR RM FEE ON RM NIGHT BASIS. FOOD BEV OTHER FEES ON TOTAL AMT BASIS.',
      },
      travelAgentCommissionParticipant: true,
      otherCharge: [{ rollawayBedCharge: 102.93, rollawayBedAvailable: true }],
      taxAndFeeDetail: '不含10%的服务费。',
    },
    parking: {
      controlledAccess: true,
      offSiteInd: { distance: 0.05, direction: 'E', time: '00:00', onSiteInd: false, offSiteInd: true },
      parkingOffSiteOnSite: { distance: 0.5, direction: 'E', time: '00:00', onSiteInd: true, offSiteInd: true },
      directionsToOffSiteParkingGarage: 'We have two parking lots on the ground and underground.',
      dailyValetParkingFee: 0,
      valetParkingTemporarilyUnavailable: true,
      carParkingAvailable: true,
      parkingDescription: 'Free parking for hotel guests, please provide license plate number when you check out',
      numberOfParkingSpaces: 80,
      valetParkingAvailable: false,
      complimentaryDailySelfParking: true,
      chargeForParking: false,
    },
  },
};

const se = {
  startDate: '2022-08-07',
  endDate: '2022-08-08',
  radius: '30',
  distanceUnit: 'MI',
  hotels: [
    {
      hotelMnemonic: 'TAOCC',
      availabilityStatus: 'OPEN',
      isCommissionable: 'YES',
      routeType: 'STRAIGHTLINE',
      lowestCashOnlyCost: {
        baseAmount: '472.62',
        excludedFeeSubTotal: '47.26',
        excludedTaxSubTotal: '31.19',
        amountAfterTax: '551.07',
        numberOfAvailableProducts: 7,
      },
      highestCashOnlyCost: {
        baseAmount: '1749.41',
        excludedFeeSubTotal: '174.94',
        excludedTaxSubTotal: '115.46',
        amountAfterTax: '2039.81',
        ratePlanType: 'RPT11',
        numberOfAvailableProducts: 9,
      },
      distance: 2.8,
      distanceKm: 4.51,
      arePackageRatesReturned: false,
      arePublicRatesIncludedIfNoAvail: false,
      attributeCodes: ['CC020', 'NSMK', 'AB010'],
      propertyCurrency: 'CNY',
      ratePlanDefinitions: [
        {
          rateRange: {
            low: { baseAmount: '472.62', excludedFeeSubTotal: '47.26', excludedTaxSubTotal: '31.19', amountAfterTax: '551.07' },
            high: { baseAmount: '1577.26', excludedFeeSubTotal: '157.73', excludedTaxSubTotal: '104.10', amountAfterTax: '1839.09' },
          },
          code: 'IDME0',
          providerDescription: 'Exclusive savings for our IHG One Rewards Members. Must be an IHG One Rewards Member to book. ',
          isPreferred: false,
        },
        {
          rateRange: {
            low: { baseAmount: '513.72', excludedFeeSubTotal: '51.37', excludedTaxSubTotal: '33.91', amountAfterTax: '599.00' },
            high: { baseAmount: '1714.41', excludedFeeSubTotal: '171.44', excludedTaxSubTotal: '113.15', amountAfterTax: '1999.00' },
          },
          code: 'IGCOR',
          providerDescription: 'BEST AVAILABLE RATE',
          types: ['RPT4', 'RPT12'],
          isPreferred: false,
        },
        {
          rateRange: {
            low: { baseAmount: '504.82', excludedFeeSubTotal: '50.48', excludedTaxSubTotal: '33.32', amountAfterTax: '588.62' },
            high: { baseAmount: '1609.46', excludedFeeSubTotal: '160.95', excludedTaxSubTotal: '106.22', amountAfterTax: '1876.63' },
          },
          code: 'IKME3',
          providerDescription: 'INCLUDES ROOM AND 1000 IHG ONE REWARDS CLUB POINTS PER NIGHT. BONUS WILL BE FULFILLED ELECTRONICALLY.',
          isPreferred: false,
        },
        {
          rateRange: {
            low: { baseAmount: '548.72', excludedFeeSubTotal: '54.87', excludedTaxSubTotal: '36.22', amountAfterTax: '639.81' },
            high: { baseAmount: '1749.41', excludedFeeSubTotal: '174.94', excludedTaxSubTotal: '115.46', amountAfterTax: '2039.81' },
          },
          code: 'IKPCM',
          providerDescription:
            'INCLUDES ROOM AND 1000 REWARDS CLUB BONUS POINTS PER NIGHT IF YOU COLLECT MILES WITH PARTICIPATING AIRLINES POINTS CONVERT INTO MILES. BONUS WILL BE FULFILLED ELECTRONICALLY.',
          types: ['RPT11', 'RPT12'],
          isPreferred: false,
        },
      ],
      brandCode: 'EX',
      preferredRateAvailable: false,
    },
    {
      hotelMnemonic: 'TAOJS',
      availabilityStatus: 'CLOSED',
      routeType: 'STRAIGHTLINE',
      distance: 7.56,
      distanceKm: 12.16,
      arePackageRatesReturned: false,
      warningRefs: [0],
      propertyCurrency: 'CNY',
      brandCode: 'EX',
      preferredRateAvailable: false,
    },
    {
      hotelMnemonic: 'TAOJN',
      availabilityStatus: 'CLOSED',
      routeType: 'STRAIGHTLINE',
      distance: 7.56,
      distanceKm: 12.16,
      arePackageRatesReturned: false,
      warningRefs: [0],
      propertyCurrency: 'CNY',
      brandCode: 'CP',
      preferredRateAvailable: false,
    },
    {
      hotelMnemonic: 'TAOJI',
      availabilityStatus: 'CLOSED',
      routeType: 'STRAIGHTLINE',
      distance: 7.56,
      distanceKm: 12.16,
      arePackageRatesReturned: false,
      warningRefs: [0],
      propertyCurrency: 'CNY',
      brandCode: 'HS',
      preferredRateAvailable: false,
    },
    {
      hotelMnemonic: 'TAOLC',
      availabilityStatus: 'OPEN',
      isCommissionable: 'YES',
      routeType: 'STRAIGHTLINE',
      lowestCashOnlyCost: {
        baseAmount: '837.91',
        excludedFeeSubTotal: '83.79',
        excludedTaxSubTotal: '55.30',
        amountAfterTax: '977.00',
        numberOfAvailableProducts: 9,
      },
      highestCashOnlyCost: {
        baseAmount: '2245.86',
        excludedFeeSubTotal: '224.59',
        excludedTaxSubTotal: '148.23',
        amountAfterTax: '2618.68',
        ratePlanType: 'RPT11',
        numberOfAvailableProducts: 9,
      },
      distance: 8.16,
      distanceKm: 13.13,
      arePackageRatesReturned: false,
      arePublicRatesIncludedIfNoAvail: false,
      attributeCodes: ['CD010', 'DD010', 'NSMK', 'CG010', 'FD010', 'AB010'],
      propertyCurrency: 'CNY',
      ratePlanDefinitions: [
        {
          rateRange: {
            low: { baseAmount: '837.91', excludedFeeSubTotal: '83.79', excludedTaxSubTotal: '55.30', amountAfterTax: '977.00' },
            high: { baseAmount: '2038.59', excludedFeeSubTotal: '203.86', excludedTaxSubTotal: '134.55', amountAfterTax: '2377.00' },
          },
          code: 'IDME0',
          providerDescription: 'Exclusive savings for our IHG One Rewards Members. Must be an IHG One Rewards Member to book. ',
          isPreferred: false,
        },
        {
          rateRange: {
            low: { baseAmount: '962.23', excludedFeeSubTotal: '96.22', excludedTaxSubTotal: '63.51', amountAfterTax: '1121.96' },
            high: { baseAmount: '1335.11', excludedFeeSubTotal: '133.51', excludedTaxSubTotal: '88.12', amountAfterTax: '1556.74' },
          },
          code: 'IGBBB',
          providerDescription: 'Full breakfast daily for up to two adults sharing a room. Supplemental fee for additional guests.',
          types: ['RPT12'],
          isPreferred: false,
        },
        {
          rateRange: {
            low: { baseAmount: '910.77', excludedFeeSubTotal: '91.08', excludedTaxSubTotal: '60.11', amountAfterTax: '1061.96' },
            high: { baseAmount: '2215.86', excludedFeeSubTotal: '221.59', excludedTaxSubTotal: '146.25', amountAfterTax: '2583.70' },
          },
          code: 'IGCOR',
          providerDescription: 'BEST AVAILABLE RATE',
          types: ['RPT4', 'RPT12'],
          isPreferred: false,
        },
        {
          rateRange: {
            low: { baseAmount: '885.25', excludedFeeSubTotal: '88.53', excludedTaxSubTotal: '58.43', amountAfterTax: '1032.21' },
            high: { baseAmount: '1228.30', excludedFeeSubTotal: '122.83', excludedTaxSubTotal: '81.07', amountAfterTax: '1432.20' },
          },
          code: 'IKME0',
          providerDescription:
            'Full breakfast daily for up to two adults sharing a room. Supplemental fee for additional guests. Exclusive savings for our IHG One Rewards Club members.',
          types: ['RPT11'],
          isPreferred: false,
        },
        {
          rateRange: {
            low: { baseAmount: '940.77', excludedFeeSubTotal: '94.08', excludedTaxSubTotal: '62.09', amountAfterTax: '1096.94' },
            high: { baseAmount: '2245.86', excludedFeeSubTotal: '224.59', excludedTaxSubTotal: '148.23', amountAfterTax: '2618.68' },
          },
          code: 'IKPCM',
          providerDescription:
            'INCLUDES ROOM AND 1000 REWARDS CLUB BONUS POINTS PER NIGHT IF YOU COLLECT MILES WITH PARTICIPATING AIRLINES POINTS CONVERT INTO MILES. BONUS WILL BE FULFILLED ELECTRONICALLY.',
          types: ['RPT11', 'RPT12'],
          isPreferred: false,
        },
      ],
      brandCode: 'UL',
      preferredRateAvailable: false,
    },
    {
      hotelMnemonic: 'TAOVC',
      availabilityStatus: 'CLOSED',
      routeType: 'STRAIGHTLINE',
      distance: 8.25,
      distanceKm: 13.27,
      arePackageRatesReturned: false,
      warningRefs: [1],
      propertyCurrency: 'CNY',
      brandCode: 'VX',
      preferredRateAvailable: false,
    },
    {
      hotelMnemonic: 'DAOXP',
      availabilityStatus: 'OPEN',
      isCommissionable: 'YES',
      routeType: 'STRAIGHTLINE',
      lowestCashOnlyCost: {
        baseAmount: '677.12',
        excludedFeeSubTotal: '67.71',
        excludedTaxSubTotal: '44.69',
        amountAfterTax: '789.52',
        numberOfAvailableProducts: 9,
      },
      highestCashOnlyCost: {
        baseAmount: '1236.00',
        excludedFeeSubTotal: '123.60',
        excludedTaxSubTotal: '81.58',
        amountAfterTax: '1441.18',
        ratePlanType: 'RPT11',
        numberOfAvailableProducts: 1,
      },
      distance: 8.87,
      distanceKm: 14.27,
      arePackageRatesReturned: false,
      arePublicRatesIncludedIfNoAvail: false,
      attributeCodes: ['NA040', 'CD010', 'GA140', 'AC090', 'HA050', 'NSMK', 'MA070'],
      propertyCurrency: 'CNY',
      ratePlanDefinitions: [
        {
          rateRange: {
            low: { baseAmount: '677.12', excludedFeeSubTotal: '67.71', excludedTaxSubTotal: '44.69', amountAfterTax: '789.52' },
            high: { baseAmount: '1045.12', excludedFeeSubTotal: '104.51', excludedTaxSubTotal: '68.98', amountAfterTax: '1218.61' },
          },
          code: 'IDME0',
          providerDescription: 'Exclusive savings for our IHG One Rewards Members. Must be an IHG One Rewards Member to book. ',
          isPreferred: false,
        },
        {
          rateRange: {
            low: { baseAmount: '737.00', excludedFeeSubTotal: '73.70', excludedTaxSubTotal: '48.64', amountAfterTax: '859.34' },
            high: { baseAmount: '1137.00', excludedFeeSubTotal: '113.70', excludedTaxSubTotal: '75.04', amountAfterTax: '1325.74' },
          },
          code: 'IGBBB',
          providerDescription: 'Full breakfast daily for up to two adults sharing a room. Supplemental fee for additional guests.',
          types: ['RPT12', 'RPT17'],
          isPreferred: false,
        },
        {
          rateRange: {
            low: { baseAmount: '736.00', excludedFeeSubTotal: '73.60', excludedTaxSubTotal: '48.58', amountAfterTax: '858.18' },
            high: { baseAmount: '1136.00', excludedFeeSubTotal: '113.60', excludedTaxSubTotal: '74.98', amountAfterTax: '1324.58' },
          },
          code: 'IGCOR',
          providerDescription: 'BEST AVAILABLE RATE',
          types: ['RPT4', 'RPT12'],
          isPreferred: false,
        },
        {
          rateRange: {
            low: { baseAmount: '896.00', excludedFeeSubTotal: '89.60', excludedTaxSubTotal: '59.14', amountAfterTax: '1044.74' },
            high: { baseAmount: '896.00', excludedFeeSubTotal: '89.60', excludedTaxSubTotal: '59.14', amountAfterTax: '1044.74' },
          },
          code: 'IKHD1',
          providerDescription: 'Baileyuan Pkg includes up to 2 ABF and 2 Baileyuan tickets',
          types: ['RPT11'],
          isPreferred: false,
        },
        {
          rateRange: {
            low: { baseAmount: '678.04', excludedFeeSubTotal: '67.80', excludedTaxSubTotal: '44.75', amountAfterTax: '790.59' },
            high: { baseAmount: '1046.04', excludedFeeSubTotal: '104.60', excludedTaxSubTotal: '69.04', amountAfterTax: '1219.68' },
          },
          code: 'IKME0',
          providerDescription:
            'Full breakfast daily for up to two adults sharing a room. Supplemental fee for additional guests. Exclusive savings for our IHG One Rewards Club members.',
          types: ['RPT11'],
          isPreferred: false,
        },
        {
          rateRange: {
            low: { baseAmount: '771.00', excludedFeeSubTotal: '77.10', excludedTaxSubTotal: '50.89', amountAfterTax: '898.99' },
            high: { baseAmount: '1171.00', excludedFeeSubTotal: '117.10', excludedTaxSubTotal: '77.29', amountAfterTax: '1365.39' },
          },
          code: 'IKPCM',
          providerDescription:
            'INCLUDES ROOM AND 1000 REWARDS CLUB BONUS POINTS PER NIGHT IF YOU COLLECT MILES WITH PARTICIPATING AIRLINES POINTS CONVERT INTO MILES. BONUS WILL BE FULFILLED ELECTRONICALLY.',
          types: ['RPT11', 'RPT12'],
          isPreferred: false,
        },
        {
          rateRange: {
            low: { baseAmount: '836.00', excludedFeeSubTotal: '83.60', excludedTaxSubTotal: '55.18', amountAfterTax: '974.78' },
            high: { baseAmount: '1236.00', excludedFeeSubTotal: '123.60', excludedTaxSubTotal: '81.58', amountAfterTax: '1441.18' },
          },
          code: 'IKWRO',
          providerDescription: 'Room with breakfasts for up to 2 adults and 1 kid. Tsingtao Beer snack package',
          types: ['RPT11', 'RPT12'],
          isPreferred: false,
        },
      ],
      brandCode: 'HI',
      preferredRateAvailable: false,
    },
    {
      hotelMnemonic: 'TAOIP',
      availabilityStatus: 'CLOSED',
      routeType: 'STRAIGHTLINE',
      distance: 9.76,
      distanceKm: 15.7,
      arePackageRatesReturned: false,
      warningRefs: [0],
      propertyCurrency: 'CNY',
      brandCode: 'EX',
      preferredRateAvailable: false,
    },
    {
      hotelMnemonic: 'DAOXR',
      availabilityStatus: 'CLOSED',
      routeType: 'STRAIGHTLINE',
      distance: 13.78,
      distanceKm: 22.17,
      arePackageRatesReturned: false,
      warningRefs: [2],
      propertyCurrency: 'CNY',
      brandCode: 'HI',
      preferredRateAvailable: false,
    },
    {
      hotelMnemonic: 'DAOCC',
      availabilityStatus: 'OPEN',
      isCommissionable: 'YES',
      routeType: 'STRAIGHTLINE',
      lowestCashOnlyCost: {
        baseAmount: '788.24',
        excludedFeeSubTotal: '78.82',
        excludedTaxSubTotal: '52.02',
        amountAfterTax: '919.08',
        numberOfAvailableProducts: 2,
      },
      highestCashOnlyCost: {
        baseAmount: '1749.41',
        excludedFeeSubTotal: '174.94',
        excludedTaxSubTotal: '115.46',
        amountAfterTax: '2039.81',
        ratePlanType: 'RPT11',
        numberOfAvailableProducts: 3,
      },
      distance: 13.96,
      distanceKm: 22.46,
      arePackageRatesReturned: false,
      arePublicRatesIncludedIfNoAvail: false,
      attributeCodes: ['CC020', 'NSMK', 'AB060'],
      propertyCurrency: 'CNY',
      ratePlanDefinitions: [
        {
          rateRange: {
            low: { baseAmount: '788.24', excludedFeeSubTotal: '78.82', excludedTaxSubTotal: '52.02', amountAfterTax: '919.08' },
            high: { baseAmount: '1577.26', excludedFeeSubTotal: '157.73', excludedTaxSubTotal: '104.10', amountAfterTax: '1839.09' },
          },
          code: 'IDME0',
          providerDescription: 'Exclusive savings for our IHG One Rewards Members. Must be an IHG One Rewards Member to book. ',
          isPreferred: false,
        },
        {
          rateRange: {
            low: { baseAmount: '856.78', excludedFeeSubTotal: '85.68', excludedTaxSubTotal: '56.55', amountAfterTax: '999.01' },
            high: { baseAmount: '1714.41', excludedFeeSubTotal: '171.44', excludedTaxSubTotal: '113.15', amountAfterTax: '1999.00' },
          },
          code: 'IGCOR',
          providerDescription: 'BEST AVAILABLE RATE',
          types: ['RPT4', 'RPT12'],
          isPreferred: false,
        },
        {
          rateRange: {
            low: { baseAmount: '820.44', excludedFeeSubTotal: '82.04', excludedTaxSubTotal: '54.15', amountAfterTax: '956.63' },
            high: { baseAmount: '1609.46', excludedFeeSubTotal: '160.95', excludedTaxSubTotal: '106.22', amountAfterTax: '1876.63' },
          },
          code: 'IKME3',
          providerDescription: 'INCLUDES ROOM AND 1000 IHG ONE REWARDS CLUB POINTS PER NIGHT. BONUS WILL BE FULFILLED ELECTRONICALLY.',
          isPreferred: false,
        },
        {
          rateRange: {
            low: { baseAmount: '891.78', excludedFeeSubTotal: '89.18', excludedTaxSubTotal: '58.86', amountAfterTax: '1039.82' },
            high: { baseAmount: '1749.41', excludedFeeSubTotal: '174.94', excludedTaxSubTotal: '115.46', amountAfterTax: '2039.81' },
          },
          code: 'IKPCM',
          providerDescription:
            'INCLUDES ROOM AND 1000 REWARDS CLUB BONUS POINTS PER NIGHT IF YOU COLLECT MILES WITH PARTICIPATING AIRLINES POINTS CONVERT INTO MILES. BONUS WILL BE FULFILLED ELECTRONICALLY.',
          types: ['RPT11', 'RPT12'],
          isPreferred: false,
        },
      ],
      brandCode: 'EX',
      preferredRateAvailable: false,
    },
    {
      hotelMnemonic: 'DAOCH',
      availabilityStatus: 'CLOSED',
      routeType: 'STRAIGHTLINE',
      distance: 14.03,
      distanceKm: 22.57,
      arePackageRatesReturned: false,
      warningRefs: [0],
      propertyCurrency: 'CNY',
      brandCode: 'CP',
      preferredRateAvailable: false,
    },
    {
      hotelMnemonic: 'DAOHA',
      availabilityStatus: 'CLOSED',
      routeType: 'STRAIGHTLINE',
      distance: 14.53,
      distanceKm: 23.38,
      arePackageRatesReturned: false,
      warningRefs: [3],
      propertyCurrency: 'CNY',
      brandCode: 'IC',
      preferredRateAvailable: false,
    },
    {
      hotelMnemonic: 'TAOJC',
      availabilityStatus: 'OPEN',
      isCommissionable: 'YES',
      routeType: 'STRAIGHTLINE',
      lowestCashOnlyCost: {
        baseAmount: '623.76',
        excludedFeeSubTotal: '62.38',
        excludedTaxSubTotal: '41.17',
        amountAfterTax: '727.31',
        numberOfAvailableProducts: 1,
      },
      highestCashOnlyCost: {
        baseAmount: '9300.98',
        excludedFeeSubTotal: '930.10',
        excludedTaxSubTotal: '613.86',
        amountAfterTax: '10844.94',
        ratePlanType: 'RPT11',
        numberOfAvailableProducts: 2,
      },
      distance: 20.25,
      distanceKm: 32.58,
      arePackageRatesReturned: false,
      arePublicRatesIncludedIfNoAvail: false,
      attributeCodes: ['NA040', 'SMK', 'FE020', 'GA140', 'HA060', 'CG020', 'DB120', 'AC010'],
      propertyCurrency: 'CNY',
      ratePlanDefinitions: [
        {
          rateRange: {
            low: { baseAmount: '623.76', excludedFeeSubTotal: '62.38', excludedTaxSubTotal: '41.17', amountAfterTax: '727.31' },
            high: { baseAmount: '8351.76', excludedFeeSubTotal: '835.18', excludedTaxSubTotal: '551.22', amountAfterTax: '9738.16' },
          },
          code: 'IDME0',
          providerDescription: 'Exclusive savings for our IHG One Rewards Members. Must be an IHG One Rewards Member to book. ',
          isPreferred: false,
        },
        {
          rateRange: {
            low: { baseAmount: '758.00', excludedFeeSubTotal: '75.80', excludedTaxSubTotal: '50.03', amountAfterTax: '883.83' },
            high: { baseAmount: '9158.00', excludedFeeSubTotal: '915.80', excludedTaxSubTotal: '604.43', amountAfterTax: '10678.23' },
          },
          code: 'IGBBB',
          providerDescription: 'Full breakfast daily for up to two adults sharing a room. Supplemental fee for additional guests.',
          types: ['RPT12', 'RPT17'],
          isPreferred: false,
        },
        {
          rateRange: {
            low: { baseAmount: '678.00', excludedFeeSubTotal: '67.80', excludedTaxSubTotal: '44.75', amountAfterTax: '790.55' },
            high: { baseAmount: '9078.00', excludedFeeSubTotal: '907.80', excludedTaxSubTotal: '599.15', amountAfterTax: '10584.95' },
          },
          code: 'IGCOR',
          providerDescription: 'BEST AVAILABLE RATE',
          types: ['RPT4', 'RPT12'],
          isPreferred: false,
        },
        {
          rateRange: {
            low: { baseAmount: '788.00', excludedFeeSubTotal: '78.80', excludedTaxSubTotal: '52.01', amountAfterTax: '918.81' },
            high: { baseAmount: '9188.00', excludedFeeSubTotal: '918.80', excludedTaxSubTotal: '606.41', amountAfterTax: '10713.21' },
          },
          code: 'IKBB1',
          providerDescription:
            'Full breakfast daily for up to two adults sharing a room. Supplemental fee for additional guests. Plus 1000 Bonus Points per night awarded electronically upon completion of the stay. ',
          types: ['RPT11', 'RPT12'],
          isPreferred: false,
        },
        {
          rateRange: {
            low: { baseAmount: '900.98', excludedFeeSubTotal: '90.10', excludedTaxSubTotal: '59.46', amountAfterTax: '1050.54' },
            high: { baseAmount: '9300.98', excludedFeeSubTotal: '930.10', excludedTaxSubTotal: '613.86', amountAfterTax: '10844.94' },
          },
          code: 'IKHD1',
          providerDescription: 'Incl Daily Breakfasts and Hot Spring Ticket for two Adults',
          types: ['RPT11'],
          isPreferred: false,
        },
        {
          rateRange: {
            low: { baseAmount: '697.36', excludedFeeSubTotal: '69.74', excludedTaxSubTotal: '46.03', amountAfterTax: '813.13' },
            high: { baseAmount: '8425.36', excludedFeeSubTotal: '842.54', excludedTaxSubTotal: '556.07', amountAfterTax: '9823.97' },
          },
          code: 'IKME0',
          providerDescription:
            'Full breakfast daily for up to two adults sharing a room. Supplemental fee for additional guests. Exclusive savings for our IHG One Rewards Club members.',
          types: ['RPT12', 'RPT17'],
          isPreferred: false,
        },
        {
          rateRange: {
            low: { baseAmount: '686.76', excludedFeeSubTotal: '68.68', excludedTaxSubTotal: '45.33', amountAfterTax: '800.77' },
            high: { baseAmount: '8834.76', excludedFeeSubTotal: '883.48', excludedTaxSubTotal: '583.09', amountAfterTax: '10301.33' },
          },
          code: 'IKME3',
          providerDescription: 'INCLUDES ROOM AND 1000 IHG ONE REWARDS CLUB POINTS PER NIGHT. BONUS WILL BE FULFILLED ELECTRONICALLY.',
          isPreferred: false,
        },
        {
          rateRange: {
            low: { baseAmount: '724.96', excludedFeeSubTotal: '72.50', excludedTaxSubTotal: '47.85', amountAfterTax: '845.31' },
            high: { baseAmount: '8452.96', excludedFeeSubTotal: '845.30', excludedTaxSubTotal: '557.90', amountAfterTax: '9856.16' },
          },
          code: 'IKME4',
          providerDescription:
            'Full breakfast daily for up to two adults sharing a room. Supplemental fee for additional guests. Plus 1000 Bonus Points per night awarded electronically upon completion of the stay. Exclusive savings for our IHG One Rewards Club members.',
          isPreferred: false,
        },
        {
          rateRange: {
            low: { baseAmount: '708.00', excludedFeeSubTotal: '70.80', excludedTaxSubTotal: '46.73', amountAfterTax: '825.53' },
            high: { baseAmount: '9108.00', excludedFeeSubTotal: '910.80', excludedTaxSubTotal: '601.13', amountAfterTax: '10619.93' },
          },
          code: 'IKPCM',
          providerDescription:
            'INCLUDES ROOM AND 1000 REWARDS CLUB BONUS POINTS PER NIGHT IF YOU COLLECT MILES WITH PARTICIPATING AIRLINES POINTS CONVERT INTO MILES. BONUS WILL BE FULFILLED ELECTRONICALLY.',
          types: ['RPT11', 'RPT12'],
          isPreferred: false,
        },
      ],
      brandCode: 'CP',
      preferredRateAvailable: false,
    },
    {
      hotelMnemonic: 'TAOQW',
      availabilityStatus: 'CLOSED',
      routeType: 'STRAIGHTLINE',
      distance: 24.17,
      distanceKm: 38.89,
      arePackageRatesReturned: false,
      warningRefs: [0],
      propertyCurrency: 'CNY',
      brandCode: 'EX',
      preferredRateAvailable: false,
    },
    {
      hotelMnemonic: 'TAOMM',
      availabilityStatus: 'CLOSED',
      routeType: 'STRAIGHTLINE',
      distance: 29.54,
      distanceKm: 47.53,
      arePackageRatesReturned: false,
      warningRefs: [2],
      propertyCurrency: 'CNY',
      brandCode: 'CP',
      preferredRateAvailable: false,
    },
  ],
  warnings: [
    { id: 0, message: 'Closed restriction on property', code: 'CRS_50013', details: [{ code: 54 }] },
    { id: 1, message: 'The property is not active', code: 'CRS_50037', details: [{ code: 9 }] },
    { id: 2, message: 'No availability for number of rooms requested', code: 'CRS_50025', details: [{ code: 142 }] },
    { id: 3, message: 'Min and max los of the property are not respected', code: 'CRS_50012', details: [{ code: 71 }] },
  ],
  isSellStrategyIncludedIfNoAvail: false,
};

export type DetailData = typeof searchData;
export type SearchData = typeof se;
