const searchResult = {
  errcode: 0,
  data: {
    triggerLimitFlag: false,
    totalPage: 13,
    pageSize: 20,
    totalCount: 245,
    list: [
      {
        DPID: 'd3db408f3d9531169a94b62ed30d17b6',
        companyName: '博达瑞（南京）科技有限公司',
        certifyType: 0,
        scale: '',
        lon: 118.695673,
        industry: '制造业',
        regcapCur: '万人民币',
        basicInfo: {
          companyInfoCount: 10,
          businessRiskCount: 0,
          semPromoCount: 0,
          basicInfoCount: 4,
          newsInfoCount: 0,
          contactCount: 2,
          recruitInfoCount: 0,
          tenderInfoCount: 0,
          patentCount: 0,
        },
        entType: '1000',
        secIndustryShort: ['汽车制造业'],
        companyLogoUrl: '',
        legalPerson: '田瑞冬',
        businessAddress: '南京市江北新区星火路14号长峰大厦1号实验楼3层B02-69室',
        hitDescription: '统一信用代码：91320191MA20D8LX72',
        companyNameWS:
          "<font color='#FF1A1A'>博</font><font color='#FF1A1A'>达</font><font color='#FF1A1A'>瑞</font>（<font color='#FF1A1A'>南</font><font color='#FF1A1A'>京</font>）科技<font color='#FF1A1A'>有</font><font color='#FF1A1A'>限</font><font color='#FF1A1A'>公</font><font color='#FF1A1A'>司</font>",
        lat: 32.156227,
        address: '南京市江北新区星火路14号长峰大厦1号实验楼3层B02-69室',
        isReceived: 0,
        entBigType: 1,
        tags: [
          { backgroundColor: '#FFEEF2', fontColor: '#F96986', desc: '2个联系方式' },
          { backgroundColor: '#FCEDD8', fontColor: '#FFA72E', desc: '存续' },
          { backgroundColor: '#F1EDF9', fontColor: '#AB73FF', desc: '民营' },
        ],
        industryMiddle: '汽车零部件及配件制造',
        esDate: '2019-11-11',
        officialWebsite: '',
        distanceStr: '',
        regcap: 500,
        entStatus: '1',
        logoDetail: { backgroundColor: '#7DB3D9', initials: 'B', shortCompanyName: '博达瑞', fontColor: '#FFFFFF' },
      },
      {
        DPID: '9ab056b572c05c240e1a0a67262e88fe',
        companyName: '南京瑞博达科技有限公司',
        certifyType: 0,
        scale: '',
        lon: 118.8528,
        industry: '科学研究和技术服务业',
        regcapCur: '万',
        basicInfo: {
          companyInfoCount: 8,
          businessRiskCount: 0,
          semPromoCount: 0,
          basicInfoCount: 1,
          newsInfoCount: 0,
          contactCount: 2,
          recruitInfoCount: 0,
          tenderInfoCount: 0,
          patentCount: 0,
        },
        entType: '1000',
        secIndustryShort: ['科技推广和应用服务业'],
        companyLogoUrl: '',
        legalPerson: '戚薇',
        businessAddress: '320823195906050246',
        hitDescription: '统一信用代码：91320113MA1XXUKWXA',
        companyNameWS:
          "<font color='#FF1A1A'>南</font><font color='#FF1A1A'>京</font><font color='#FF1A1A'>瑞</font><font color='#FF1A1A'>博</font><font color='#FF1A1A'>达</font>科技<font color='#FF1A1A'>有</font><font color='#FF1A1A'>限</font><font color='#FF1A1A'>公</font><font color='#FF1A1A'>司</font>",
        lat: 32.108233,
        address: '320823195906050246',
        isReceived: 0,
        entBigType: 1,
        tags: [
          { backgroundColor: '#FFEEF2', fontColor: '#F96986', desc: '2个联系方式' },
          { backgroundColor: '#FCEDD8', fontColor: '#FFA72E', desc: '存续' },
          { backgroundColor: '#F1EDF9', fontColor: '#AB73FF', desc: '民营' },
        ],
        industryMiddle: '其他科技推广服务业',
        esDate: '2019-02-22',
        officialWebsite: '',
        distanceStr: '',
        regcap: 101,
        entStatus: '1',
        logoDetail: { backgroundColor: '#BC9EDD', initials: 'R', shortCompanyName: '瑞博达', fontColor: '#FFFFFF' },
      },
      {
        DPID: 'a22a629eb95b21c9bb7057b6782652fb',
        companyName: '北京缔联科技有限公司',
        certifyType: 0,
        scale: '50-99人',
        lon: 116.317663,
        industry: '科学研究和技术服务业',
        regcapCur: '万人民币',
        basicInfo: {
          companyInfoCount: 75,
          businessRiskCount: 10,
          semPromoCount: 1025,
          basicInfoCount: 37,
          newsInfoCount: 0,
          contactCount: 22,
          recruitInfoCount: 170,
          tenderInfoCount: 0,
          patentCount: 100,
        },
        entType: '1000',
        secIndustryShort: ['科技推广和应用服务业'],
        companyLogoUrl: 'https://static-koios.hsmob.com/cio/production_img/070652446be8559047ca03c9d4c4c4c0.png',
        legalPerson: '于震寰',
        businessAddress: '北京市海淀区西小府23号3幢1层172',
        hitDescription:
          "历史名称：思创合璞（北<font color='#FF1A1A'>京</font>）创业咨询<font color='#FF1A1A'>有</font><font color='#FF1A1A'>限</font><font color='#FF1A1A'>公</font><font color='#FF1A1A'>司</font>",
        companyNameWS:
          "北<font color='#FF1A1A'>京</font>缔联科技<font color='#FF1A1A'>有</font><font color='#FF1A1A'>限</font><font color='#FF1A1A'>公</font><font color='#FF1A1A'>司</font>",
        lat: 39.983785,
        address: '北京市海淀区西小府23号3幢1层172',
        isReceived: 0,
        entBigType: 1,
        tags: [
          { backgroundColor: '#FFEEF2', fontColor: '#F96986', desc: '22个联系方式' },
          { backgroundColor: '#FCEDD8', fontColor: '#FFA72E', desc: '存续' },
          { backgroundColor: '#F1EDF9', fontColor: '#AB73FF', desc: '高新企业' },
          { backgroundColor: '#EBF0FE', fontColor: '#4F7AFD', desc: 'B+轮' },
          { backgroundColor: '#F1EDF9', fontColor: '#AB73FF', desc: '民营' },
        ],
        industryMiddle: '其他科技推广服务业',
        esDate: '2014-07-22',
        officialWebsite: 'www.feeclouds.com',
        distanceStr: '',
        regcap: 1000,
        entStatus: '1',
        logoDetail: { backgroundColor: '#7DB3D9', initials: 'D', shortCompanyName: '缔联科技', fontColor: '#FFFFFF' },
      },
      {
        DPID: 'e82d0661259aed2ae232dc9b267ac5d1',
        companyName: '广州市朗普光电科技有限公司',
        certifyType: 0,
        scale: '100-499人',
        lon: 113.230626,
        industry: '科学研究和技术服务业',
        regcapCur: '万人民币',
        basicInfo: {
          companyInfoCount: 19,
          businessRiskCount: 0,
          semPromoCount: 705,
          basicInfoCount: 343,
          newsInfoCount: 0,
          contactCount: 27,
          recruitInfoCount: 4,
          tenderInfoCount: 1,
          patentCount: 54,
        },
        entType: '1000',
        secIndustryShort: ['研究和试验发展'],
        companyLogoUrl: 'https://static-koios.hsmob.com/cio/production_img/a39ec717cd7e8625f8d811b588cf87e6.jpg',
        legalPerson: '谢明理',
        businessAddress: '广州市荔湾区永乐路23号143房',
        hitDescription:
          "网络推广：浸没式紫外线消毒器水箱自洁消毒器WTS,中红外激光器,深圳市景泰源光电科技,水性漆干燥,热弯玻璃展示柜,红外线塑料,取暖器加热灯管,上海源阅物流<font color='#FF1A1A'>有限</font><font color='#FF1A1A'>公司</font>,上海洋启物流,重庆紫外线消毒设备,红外线加热管,UV光解废气处理,紫外线灯紫外杀菌模块,油漆烘干,红外灯,优威,上海雷兴弯管",
        companyNameWS:
          "广州市朗普光电科技<font color='#FF1A1A'>有</font><font color='#FF1A1A'>限</font><font color='#FF1A1A'>公</font><font color='#FF1A1A'>司</font>",
        lat: 23.095381,
        address: '广州市荔湾区永乐路23号143房',
        isReceived: 0,
        entBigType: 1,
        tags: [
          { backgroundColor: '#FFEEF2', fontColor: '#F96986', desc: '27个联系方式' },
          { backgroundColor: '#FCEDD8', fontColor: '#FFA72E', desc: '存续' },
          { backgroundColor: '#F1EDF9', fontColor: '#AB73FF', desc: '纳税A级' },
          { backgroundColor: '#F1EDF9', fontColor: '#AB73FF', desc: '民营' },
        ],
        industryMiddle: '工程和技术研究和试验发展',
        esDate: '2009-04-17',
        officialWebsite: 'www.朗普.com',
        distanceStr: '',
        regcap: 1000,
        entStatus: '1',
        logoDetail: { backgroundColor: '#8CA3CD', initials: 'L', shortCompanyName: '朗普光电', fontColor: '#FFFFFF' },
      },
      {
        DPID: '2c05523ef5062571ba09e826d2a8ccf',
        companyName: '河南超之源商贸有限公司',
        certifyType: 0,
        scale: '50-99人',
        lon: 113.717,
        industry: '批发和零售业',
        regcapCur: '万人民币',
        basicInfo: {
          companyInfoCount: 20,
          businessRiskCount: 0,
          semPromoCount: 21,
          basicInfoCount: 12,
          newsInfoCount: 0,
          contactCount: 12,
          recruitInfoCount: 2,
          tenderInfoCount: 2,
          patentCount: 6,
        },
        entType: '1000',
        secIndustryShort: ['批发业'],
        companyLogoUrl: '',
        legalPerson: '王建超',
        businessAddress: '河南省郑州市金水区郑汴路127号院4号楼2单元26层2602号',
        hitDescription:
          "网络推广：天津礼品定制,安徽<font color='#FF1A1A'>博达</font>礼品,广州市金里来礼品,无锡瑞丰<font color='#FF1A1A'>达</font>礼品,广州市鑫天礼品,太和县乐意礼品销售,湖南尚虹礼品贸易一,重庆天韵礼品,佛山市南海区尊礼礼品贸易,广州咪妮酷礼品,烟台凯瑞礼品,中山市尚礼礼品,重庆谢礼汇礼品,<font color='#FF1A1A'>有限</font><font color='#FF1A1A'>公司</font>,<font color='#FF1A1A'>南京</font>博西尼亚礼品",
        companyNameWS:
          "河<font color='#FF1A1A'>南</font>超之源商贸<font color='#FF1A1A'>有</font><font color='#FF1A1A'>限</font><font color='#FF1A1A'>公</font><font color='#FF1A1A'>司</font>",
        lat: 34.745594,
        address: '河南省郑州市金水区郑汴路127号院4号楼2单元26层2602号',
        isReceived: 0,
        entBigType: 1,
        tags: [
          { backgroundColor: '#FFEEF2', fontColor: '#F96986', desc: '12个联系方式' },
          { backgroundColor: '#FCEDD8', fontColor: '#FFA72E', desc: '存续' },
          { backgroundColor: '#F1EDF9', fontColor: '#AB73FF', desc: '纳税A级' },
          { backgroundColor: '#F1EDF9', fontColor: '#AB73FF', desc: '民营' },
        ],
        industryMiddle: '矿产品、建材及化工产品批发',
        esDate: '2017-05-03',
        officialWebsite: 'www.chaozhiyuan.cn',
        distanceStr: '',
        regcap: 500,
        entStatus: '1',
        logoDetail: { backgroundColor: '#7DB3D9', initials: 'C', shortCompanyName: '超之源', fontColor: '#FFFFFF' },
      },
      {
        DPID: '29a3c95d15a511046c5f0c54909c5dee',
        companyName: '淄博爱尔玛消防器材有限公司',
        certifyType: 0,
        scale: '0-49人',
        lon: 118.250778,
        industry: '制造业',
        regcapCur: '万人民币',
        basicInfo: {
          companyInfoCount: 91,
          businessRiskCount: 22,
          semPromoCount: 184,
          basicInfoCount: 31,
          newsInfoCount: 0,
          contactCount: 23,
          recruitInfoCount: 53,
          tenderInfoCount: 22,
          patentCount: 163,
        },
        entType: '1000',
        secIndustryShort: ['专用设备制造业'],
        companyLogoUrl: 'https://static-koios.hsmob.com/cio/production_img/1d1008d57f3df4d32d091d9d2e3968a4.jpg',
        legalPerson: '王怀建',
        businessAddress: '临淄区稷下街道王家村工业园',
        hitDescription:
          "历史名称：淄<font color='#FF1A1A'>博</font>市临淄永<font color='#FF1A1A'>达</font>消防器材<font color='#FF1A1A'>有</font><font color='#FF1A1A'>限</font><font color='#FF1A1A'>公</font><font color='#FF1A1A'>司</font>",
        companyNameWS:
          "淄<font color='#FF1A1A'>博</font>爱尔玛消防器材<font color='#FF1A1A'>有</font><font color='#FF1A1A'>限</font><font color='#FF1A1A'>公</font><font color='#FF1A1A'>司</font>",
        lat: 36.826908,
        address: '临淄区稷下街道王家村工业园',
        isReceived: 0,
        entBigType: 1,
        tags: [
          { backgroundColor: '#FFEEF2', fontColor: '#F96986', desc: '23个联系方式' },
          { backgroundColor: '#FCEDD8', fontColor: '#FFA72E', desc: '存续' },
          { backgroundColor: '#F1EDF9', fontColor: '#AB73FF', desc: '纳税A级' },
          { backgroundColor: '#F1EDF9', fontColor: '#AB73FF', desc: '民营' },
        ],
        industryMiddle: '医疗仪器设备及器械制造',
        esDate: '2003-01-23',
        officialWebsite: 'www.armxf.com',
        distanceStr: '',
        regcap: 8000,
        entStatus: '1',
        logoDetail: { backgroundColor: '#7DB3D9', initials: 'A', shortCompanyName: '爱尔玛', fontColor: '#FFFFFF' },
      },
      {
        DPID: '20be04ccd017500bf5d41fbad14b2372',
        companyName: '济南永仓仓储设备有限公司',
        certifyType: 0,
        scale: '',
        lon: 117.009611,
        industry: '批发和零售业',
        regcapCur: '万',
        basicInfo: {
          companyInfoCount: 11,
          businessRiskCount: 0,
          semPromoCount: 357,
          basicInfoCount: 7,
          newsInfoCount: 0,
          contactCount: 6,
          recruitInfoCount: 0,
          tenderInfoCount: 0,
          patentCount: 0,
        },
        entType: '1000',
        secIndustryShort: ['批发业'],
        companyLogoUrl: '',
        legalPerson: '周刚',
        businessAddress: '山东省济南市历下区东关大街9号海右商厦B225',
        hitDescription:
          "网络推广：河南仓库货架,北京货架价格,北京中型货架,扬州<font color='#FF1A1A'>瑞</font>途钢结构<font color='#FF1A1A'>有限</font><font color='#FF1A1A'>公司</font>,深圳出口卡板厂,北京盛世铭<font color='#FF1A1A'>达</font>货架,药品仓库货架,昆山周转箱,天津东腾货架,中型仓储货架<font color='#FF1A1A'>公司</font>,东莞市兴力货架,层板货架,钢结构平台货架,<font color='#FF1A1A'>南京</font>仓库货架销售,辽宁重型货架,价格,服装货架",
        companyNameWS:
          "济<font color='#FF1A1A'>南</font>永仓仓储设备<font color='#FF1A1A'>有</font><font color='#FF1A1A'>限</font><font color='#FF1A1A'>公</font><font color='#FF1A1A'>司</font>",
        lat: 36.694041,
        address: '山东省济南市历下区东关大街9号海右商厦B225',
        isReceived: 0,
        entBigType: 1,
        tags: [
          { backgroundColor: '#FFEEF2', fontColor: '#F96986', desc: '6个联系方式' },
          { backgroundColor: '#FCEDD8', fontColor: '#FFA72E', desc: '存续' },
          { backgroundColor: '#F1EDF9', fontColor: '#AB73FF', desc: '民营' },
        ],
        industryMiddle: '机械设备、五金产品及电子产品批发',
        esDate: '2018-05-08',
        officialWebsite: 'www.yongcanghuojia.com',
        distanceStr: '',
        regcap: 300,
        entStatus: '1',
        logoDetail: { backgroundColor: '#84CAB0', initials: 'Y', shortCompanyName: '永仓仓储', fontColor: '#FFFFFF' },
      },
      {
        DPID: '5a0a4816dbc4fc43dfd93160a984e5ec',
        companyName: '日照市承浩木业有限公司',
        certifyType: 0,
        scale: '100-499人',
        lon: 119.241799,
        industry: '制造业',
        regcapCur: '万',
        basicInfo: {
          companyInfoCount: 17,
          businessRiskCount: 0,
          semPromoCount: 925,
          basicInfoCount: 912,
          newsInfoCount: 0,
          contactCount: 29,
          recruitInfoCount: 0,
          tenderInfoCount: 0,
          patentCount: 0,
        },
        entType: '1000',
        secIndustryShort: ['木材加工和木、竹、藤、棕、草制品业'],
        companyLogoUrl: '',
        legalPerson: '张林',
        businessAddress: '山东省日照市岚山区碑廓镇傅家官庄村',
        hitDescription:
          "网络推广：沙县富森木材加工厂,上海为胜木业,曹县三榜木业,曹县佳发木业,巴彦县峰<font color='#FF1A1A'>达</font>木材加工厂,文安县金润<font color='#FF1A1A'>达</font>木业,上海逸琛木业,郯城县广源木业,白松,济南木材市场价格,木业<font color='#FF1A1A'>有限</font><font color='#FF1A1A'>公司</font>,乌审旗和森木业,宁城县国成木业,黎平县育洞木材加工厂,重庆沛迪木业,颍上县森强木材加工",
        companyNameWS:
          "日照市承浩木业<font color='#FF1A1A'>有</font><font color='#FF1A1A'>限</font><font color='#FF1A1A'>公</font><font color='#FF1A1A'>司</font>",
        lat: 35.169006,
        address: '山东省日照市岚山区碑廓镇傅家官庄村',
        isReceived: 0,
        entBigType: 1,
        tags: [
          { backgroundColor: '#FFEEF2', fontColor: '#F96986', desc: '29个联系方式' },
          { backgroundColor: '#FCEDD8', fontColor: '#FFA72E', desc: '存续' },
          { backgroundColor: '#F1EDF9', fontColor: '#AB73FF', desc: '民营' },
        ],
        industryMiddle: '木材加工',
        esDate: '2018-08-23',
        officialWebsite: 'www.rzchmy.com',
        distanceStr: '',
        regcap: 300,
        entStatus: '1',
        logoDetail: { backgroundColor: '#7DB3D9', initials: 'C', shortCompanyName: '承浩木业', fontColor: '#FFFFFF' },
      },
      {
        DPID: 'f2b100c05ec0dd9b6067b7ea8cbfb466',
        companyName: '北京禹道科技集团有限公司',
        certifyType: 0,
        scale: '50-99人',
        lon: 116.28771,
        industry: '科学研究和技术服务业',
        regcapCur: '万人民币',
        basicInfo: {
          companyInfoCount: 48,
          businessRiskCount: 1,
          semPromoCount: 704,
          basicInfoCount: 23,
          newsInfoCount: 0,
          contactCount: 9,
          recruitInfoCount: 28,
          tenderInfoCount: 0,
          patentCount: 10,
        },
        entType: '1000',
        secIndustryShort: ['科技推广和应用服务业'],
        companyLogoUrl: '',
        legalPerson: '石怀英',
        businessAddress: '北京市海淀区莲花池东路31号中裕世纪大酒店B457',
        hitDescription:
          "历史名称：北<font color='#FF1A1A'>京</font>禹道广告<font color='#FF1A1A'>有</font><font color='#FF1A1A'>限</font><font color='#FF1A1A'>公</font><font color='#FF1A1A'>司</font>",
        companyNameWS:
          "北<font color='#FF1A1A'>京</font>禹道科技集团<font color='#FF1A1A'>有</font><font color='#FF1A1A'>限</font><font color='#FF1A1A'>公</font><font color='#FF1A1A'>司</font>",
        lat: 39.822489,
        address: '北京市海淀区莲花池东路31号中裕世纪大酒店B457',
        isReceived: 0,
        entBigType: 1,
        tags: [
          { backgroundColor: '#FFEEF2', fontColor: '#F96986', desc: '9个联系方式' },
          { backgroundColor: '#FCEDD8', fontColor: '#FFA72E', desc: '存续' },
          { backgroundColor: '#F1EDF9', fontColor: '#AB73FF', desc: '民营' },
        ],
        industryMiddle: '其他科技推广服务业',
        esDate: '2015-03-17',
        officialWebsite: 'www.yudaojituan.com.cn',
        distanceStr: '',
        regcap: 1000,
        entStatus: '1',
        logoDetail: { backgroundColor: '#84CAB0', initials: 'Y', shortCompanyName: '禹道科技', fontColor: '#FFFFFF' },
      },
      {
        DPID: '96ad8c21fc8bbb52e022a45af53d7510',
        companyName: '齐齐哈尔市欧爱尔环保工程有限公司',
        certifyType: 0,
        scale: '',
        lon: 123.954966,
        industry: '建筑业',
        regcapCur: '万人民币',
        basicInfo: {
          companyInfoCount: 27,
          businessRiskCount: 0,
          semPromoCount: 179,
          basicInfoCount: 2,
          newsInfoCount: 0,
          contactCount: 5,
          recruitInfoCount: 0,
          tenderInfoCount: 0,
          patentCount: 6,
        },
        entType: '1000',
        secIndustryShort: ['土木工程建筑业'],
        companyLogoUrl: '',
        legalPerson: '陈树发',
        businessAddress: '齐齐哈尔龙沙区永青小区9号楼',
        hitDescription:
          "网络推广：BAIFENGHUANB<font color='#FF1A1A'>AO</font>,南京龙源环保,福建威腾环保,蓝科环保,荆门节能环保技术,非环保<font color='#FF1A1A'>,环</font><font color='#FF1A1A'>保有</font>限公司,新型节能工程,萧阳环保,珠海环保,力华环保,光宇环保,西安某某环保,永能环保,广东省东莞市厨源节能环保,环<font color='#FF1A1A'>保工</font>程公司,暖树环保,化工节能",
        companyNameWS:
          "齐齐哈尔市欧爱尔环保工程<font color='#FF1A1A'>有</font><font color='#FF1A1A'>限</font><font color='#FF1A1A'>公</font><font color='#FF1A1A'>司</font>",
        lat: 47.337801,
        address: '齐齐哈尔龙沙区永青小区9号楼',
        isReceived: 0,
        entBigType: 1,
        tags: [
          { backgroundColor: '#FFEEF2', fontColor: '#F96986', desc: '5个联系方式' },
          { backgroundColor: '#FCEDD8', fontColor: '#FFA72E', desc: '存续' },
          { backgroundColor: '#F1EDF9', fontColor: '#AB73FF', desc: '民营' },
        ],
        industryMiddle: '节能环保工程施工',
        esDate: '2016-12-14',
        officialWebsite: '',
        distanceStr: '',
        regcap: 500,
        entStatus: '1',
        logoDetail: { backgroundColor: '#BC9EDD', initials: 'O', shortCompanyName: '欧爱尔', fontColor: '#FFFFFF' },
      },
      {
        DPID: '06da96226a525a395257a73d2a401109',
        companyName: '重庆致茂物流有限公司',
        certifyType: 0,
        scale: '0-49人',
        lon: 106.655249,
        industry: '交通运输、仓储和邮政业',
        regcapCur: '万',
        basicInfo: {
          companyInfoCount: 23,
          businessRiskCount: 0,
          semPromoCount: 266,
          basicInfoCount: 22,
          newsInfoCount: 0,
          contactCount: 13,
          recruitInfoCount: 0,
          tenderInfoCount: 0,
          patentCount: 1,
        },
        entType: '1000',
        secIndustryShort: ['道路运输业'],
        companyLogoUrl: '',
        legalPerson: '冯靖翔',
        businessAddress: '重庆市江北区铁山坪街道港城工业园区A区1栋28号',
        hitDescription:
          "网络推广：重庆汉<font color='#FF1A1A'>博</font>物流<font color='#FF1A1A'>有限</font><font color='#FF1A1A'>公司</font>,吉木萨尔县万通物流运输,合肥利达物流<font color='#FF1A1A'>有限</font><font color='#FF1A1A'>公司</font>,日照最大的物流<font color='#FF1A1A'>公司</font>,营口德源物流<font color='#FF1A1A'>有限</font><font color='#FF1A1A'>公司</font>,<font color='#FF1A1A'>南京</font>物流<font color='#FF1A1A'>公司</font>丨<font color='#FF1A1A'>南京</font>专线物流<font color='#FF1A1A'>公司</font>丨<font color='#FF1A1A'>南京</font>长途物流<font color='#FF1A1A'>公司</font>,重庆新帆物流,攀枝花庆伟物流,货物运输,重庆旗鼎货运,重庆大件行李运输,泗县虹乡物流运输",
        companyNameWS:
          "重庆致茂物流<font color='#FF1A1A'>有</font><font color='#FF1A1A'>限</font><font color='#FF1A1A'>公</font><font color='#FF1A1A'>司</font>",
        lat: 29.625247,
        address: '重庆市江北区铁山坪街道港城工业园区A区1栋28号',
        isReceived: 0,
        entBigType: 1,
        tags: [
          { backgroundColor: '#FFEEF2', fontColor: '#F96986', desc: '13个联系方式' },
          { backgroundColor: '#FCEDD8', fontColor: '#FFA72E', desc: '存续' },
          { backgroundColor: '#F1EDF9', fontColor: '#AB73FF', desc: '民营' },
        ],
        industryMiddle: '道路货物运输',
        esDate: '2010-09-02',
        officialWebsite: 'www.cqzmwl.com.cn',
        distanceStr: '',
        regcap: 500,
        entStatus: '1',
        logoDetail: { backgroundColor: '#84CAB0', initials: 'Z', shortCompanyName: '致茂物流', fontColor: '#FFFFFF' },
      },
      {
        DPID: '12b54b63807a6b64e86fd23934fa3af3',
        companyName: '北京天相财富管理顾问有限公司青岛分公司',
        certifyType: 0,
        scale: '',
        lon: 120.183115,
        industry: '金融业',
        regcapCur: '',
        basicInfo: {
          companyInfoCount: 7,
          businessRiskCount: 0,
          semPromoCount: 409,
          basicInfoCount: 9,
          newsInfoCount: 0,
          contactCount: 2,
          recruitInfoCount: 0,
          tenderInfoCount: 0,
          patentCount: 0,
        },
        entType: '2000',
        secIndustryShort: ['其他金融业'],
        companyLogoUrl: '',
        legalPerson: '张大堃',
        businessAddress: '山东省青岛市黄岛区长江中路唐宁国际16层1601',
        hitDescription:
          "网络推广：深圳市华银学苑投资,点差,深圳市华欣投资,深圳市嘉华<font color='#FF1A1A'>达</font>投资,a股,揭西县嘉信投资咨询,浙江田中精机深圳,上海钦则投资咨询,深圳市楚晟丰投资,投资顾问<font color='#FF1A1A'>公司</font>,深圳道格十号体育投资合伙企业（<font color='#FF1A1A'>有限</font>合伙）,<font color='#FF1A1A'>公司</font>顾问,珠海市斯巴达投资咨询,中山市恒峰投资咨询",
        companyNameWS:
          "北<font color='#FF1A1A'>京</font>天相财富管理顾问<font color='#FF1A1A'>有</font><font color='#FF1A1A'>限</font><font color='#FF1A1A'>公</font><font color='#FF1A1A'>司</font>青岛分<font color='#FF1A1A'>公</font><font color='#FF1A1A'>司</font>",
        lat: 35.953088,
        address: '山东省青岛市黄岛区长江中路唐宁国际16层1601',
        isReceived: 0,
        entBigType: 1,
        tags: [
          { backgroundColor: '#FFEEF2', fontColor: '#F96986', desc: '2个联系方式' },
          { backgroundColor: '#FCEDD8', fontColor: '#FFA72E', desc: '存续' },
          { backgroundColor: '#F1EDF9', fontColor: '#AB73FF', desc: '民营' },
        ],
        industryMiddle: '其他未列明金融业',
        esDate: '2018-12-19',
        officialWebsite: 'www.tianxiang09.com',
        distanceStr: '',
        regcap: '',
        entStatus: '1',
        logoDetail: { backgroundColor: '#84CAB0', initials: 'T', shortCompanyName: '天相财富', fontColor: '#FFFFFF' },
      },
      {
        DPID: '6e54b8f39a90f04ca39c32df139ba70a',
        companyName: '河南省脱颖实业有限公司',
        certifyType: 0,
        scale: '500-999人',
        lon: 113.803252,
        industry: '科学研究和技术服务业',
        regcapCur: '万人民币',
        basicInfo: {
          companyInfoCount: 90,
          businessRiskCount: 7,
          semPromoCount: 402,
          basicInfoCount: 32,
          newsInfoCount: 27,
          contactCount: 18,
          recruitInfoCount: 8,
          tenderInfoCount: 80,
          patentCount: 115,
        },
        entType: '1000',
        secIndustryShort: ['专业技术服务业'],
        companyLogoUrl: '',
        legalPerson: '程舒秋',
        businessAddress: '郑州市郑东新区龙子湖湖心环路新西兰农牧研发中心8层',
        hitDescription:
          "网络推广：常州物流运输,国内物流,深圳市特日<font color='#FF1A1A'>达</font>物流,呼和浩特物流<font color='#FF1A1A'>公司</font>哪家好,盐城市远帆物流,多年的货物运输,物流运输系统,<font color='#FF1A1A'>南京</font>碧宇物流,小城市的大型物流,五家渠韵达快运,邯郸市邯钢集团汇<font color='#FF1A1A'>达</font>汽车运输,江西福林物流,济南远威物流运输<font color='#FF1A1A'>有限</font><font color='#FF1A1A'>公司</font>,东营市华远物流,药品运输箱",
        companyNameWS:
          "河<font color='#FF1A1A'>南</font>省脱颖实业<font color='#FF1A1A'>有</font><font color='#FF1A1A'>限</font><font color='#FF1A1A'>公</font><font color='#FF1A1A'>司</font>",
        lat: 34.796727,
        address: '郑州市郑东新区龙子湖湖心环路新西兰农牧研发中心8层',
        isReceived: 0,
        entBigType: 1,
        tags: [
          { backgroundColor: '#FFEEF2', fontColor: '#F96986', desc: '18个联系方式' },
          { backgroundColor: '#FCEDD8', fontColor: '#FFA72E', desc: '存续' },
          { backgroundColor: '#F1EDF9', fontColor: '#AB73FF', desc: '高新企业' },
          { backgroundColor: '#F1EDF9', fontColor: '#AB73FF', desc: '纳税A级' },
          { backgroundColor: '#F1EDF9', fontColor: '#AB73FF', desc: '民营' },
        ],
        industryMiddle: '工程技术与设计服务',
        esDate: '1997-06-19',
        officialWebsite: 'www.tuoying.com.cn',
        distanceStr: '',
        regcap: 5000,
        entStatus: '1',
        logoDetail: { backgroundColor: '#84CAB0', initials: 'T', shortCompanyName: '脱颖实业', fontColor: '#FFFFFF' },
      },
      {
        DPID: '6cf4bb903ffd32c51dfb072ffadaf29a',
        companyName: '好买财富管理股份有限公司',
        certifyType: 0,
        scale: '500-999人',
        lon: 121.517512,
        industry: '金融业',
        regcapCur: '万人民币',
        basicInfo: {
          companyInfoCount: 132,
          businessRiskCount: 12,
          semPromoCount: 2422,
          basicInfoCount: 57,
          newsInfoCount: 58,
          contactCount: 31,
          recruitInfoCount: 1195,
          tenderInfoCount: 0,
          patentCount: 89,
        },
        entType: '1000',
        secIndustryShort: ['资本市场服务'],
        companyLogoUrl: 'https://static-koios.hsmob.com/cio/production_img/29a1e934edc9412752e8d47ae79f50fe.png',
        legalPerson: '杨文斌',
        businessAddress: '上海浦东新区浦东南路1118号9楼',
        hitDescription:
          "历史名称：上海好买信投资管理<font color='#FF1A1A'>有</font><font color='#FF1A1A'>限</font><font color='#FF1A1A'>公</font><font color='#FF1A1A'>司</font>",
        companyNameWS:
          "好买财富管理股份<font color='#FF1A1A'>有</font><font color='#FF1A1A'>限</font><font color='#FF1A1A'>公</font><font color='#FF1A1A'>司</font>",
        lat: 31.227078,
        address: '上海浦东新区浦东南路1118号9楼',
        isReceived: 0,
        entBigType: 1,
        tags: [
          { backgroundColor: '#FFEEF2', fontColor: '#F96986', desc: '31个联系方式' },
          { backgroundColor: '#FCEDD8', fontColor: '#FFA72E', desc: '存续' },
          { backgroundColor: '#F1EDF9', fontColor: '#AB73FF', desc: '高新企业' },
          { backgroundColor: '#F1EDF9', fontColor: '#AB73FF', desc: '纳税A级' },
          { backgroundColor: '#EBF0FE', fontColor: '#4F7AFD', desc: '三板' },
          { backgroundColor: '#F1EDF9', fontColor: '#AB73FF', desc: '民营' },
        ],
        industryMiddle: '其他资本市场服务',
        esDate: '2007-07-18',
        officialWebsite: 'www.howbuy.com',
        distanceStr: '',
        regcap: 34655.736,
        entStatus: '1',
        logoDetail: { backgroundColor: '#8CA3CD', initials: 'H', shortCompanyName: '好买', fontColor: '#FFFFFF' },
      },
      {
        DPID: '01e756660365fcc0b4aa2e04cc436547',
        companyName: '天津东腾货架有限公司',
        certifyType: 0,
        scale: '1000人以上',
        lon: 117.23436,
        industry: '制造业',
        regcapCur: '万人民币',
        basicInfo: {
          companyInfoCount: 21,
          businessRiskCount: 1,
          semPromoCount: 93,
          basicInfoCount: 10,
          newsInfoCount: 0,
          contactCount: 7,
          recruitInfoCount: 1,
          tenderInfoCount: 1,
          patentCount: 2,
        },
        entType: '1000',
        secIndustryShort: ['金属制品业'],
        companyLogoUrl: '',
        legalPerson: '王世界',
        businessAddress: '天津市北辰区小淀镇秀林园东四条增2号',
        hitDescription:
          "网络推广：新疆塑料托盘,中山重型货架,中型仓储货架<font color='#FF1A1A'>公司</font>,安徽阁楼货架,天津钛合金货架,郑州货架厂家,服装货架,北京巨立货架,鸿<font color='#FF1A1A'>瑞</font>塑料制品（深圳）<font color='#FF1A1A'>有限</font><font color='#FF1A1A'>公司</font>,塑料吹瓶机价格,仓库货架厂,天津货架厂家,北京元利源货架,天津货架<font color='#FF1A1A'>公司</font>名录,武汉塑料栈板,平台货架,珠海货架厂",
        companyNameWS:
          "天津东腾货架<font color='#FF1A1A'>有</font><font color='#FF1A1A'>限</font><font color='#FF1A1A'>公</font><font color='#FF1A1A'>司</font>",
        lat: 39.246685,
        address: '天津市北辰区小淀镇秀林园东四条增2号',
        isReceived: 0,
        entBigType: 1,
        tags: [
          { backgroundColor: '#FFEEF2', fontColor: '#F96986', desc: '7个联系方式' },
          { backgroundColor: '#FCEDD8', fontColor: '#FFA72E', desc: '存续' },
          { backgroundColor: '#F1EDF9', fontColor: '#AB73FF', desc: '纳税A级' },
          { backgroundColor: '#F1EDF9', fontColor: '#AB73FF', desc: '民营' },
        ],
        industryMiddle: '结构性金属制品制造',
        esDate: '2015-08-04',
        officialWebsite: 'www.tjdthuojia.com',
        distanceStr: '',
        regcap: 3650,
        entStatus: '1',
        logoDetail: { backgroundColor: '#7DB3D9', initials: 'D', shortCompanyName: '东腾货架', fontColor: '#FFFFFF' },
      },
      {
        DPID: '37566e33a2f1f18d21f9bae3ebef245a',
        companyName: '路亚绝热材料河北有限公司',
        certifyType: 0,
        scale: '100-499人',
        lon: 116.537059,
        industry: '制造业',
        regcapCur: '万人民币',
        basicInfo: {
          companyInfoCount: 17,
          businessRiskCount: 8,
          semPromoCount: 243,
          basicInfoCount: 121,
          newsInfoCount: 0,
          contactCount: 19,
          recruitInfoCount: 2,
          tenderInfoCount: 4,
          patentCount: 114,
        },
        entType: '1000',
        secIndustryShort: ['非金属矿物制品业'],
        companyLogoUrl: '',
        legalPerson: '王建',
        businessAddress: '大城县王权村',
        hitDescription:
          "商标：路亚,金莱斯,圣红安,LUYA-RUBBER,科莱美 K,亚德美,渡肯,凯德恩 K,敏乐斯,KENT FIEX,普力森,<font color='#FF1A1A'>京</font>格斯,康普乐斯,莱森美壳,泛亚德美,奥斯福,雅乐福,凯特恩",
        companyNameWS:
          "路亚绝热材料河北<font color='#FF1A1A'>有</font><font color='#FF1A1A'>限</font><font color='#FF1A1A'>公</font><font color='#FF1A1A'>司</font>",
        lat: 38.564981,
        address: '大城县王权村',
        isReceived: 0,
        entBigType: 1,
        tags: [
          { backgroundColor: '#FFEEF2', fontColor: '#F96986', desc: '19个联系方式' },
          { backgroundColor: '#FCEDD8', fontColor: '#FFA72E', desc: '存续' },
          { backgroundColor: '#F1EDF9', fontColor: '#AB73FF', desc: '纳税A级' },
          { backgroundColor: '#F1EDF9', fontColor: '#AB73FF', desc: '民营' },
        ],
        industryMiddle: '砖瓦、石材等建筑材料制造',
        esDate: '2015-08-24',
        officialWebsite: 'www.luyahb.com',
        distanceStr: '',
        regcap: 1088,
        entStatus: '1',
        logoDetail: { backgroundColor: '#8CA3CD', initials: 'L', shortCompanyName: '路亚绝热', fontColor: '#FFFFFF' },
      },
      {
        DPID: 'f3a0e331ddef34511927000776934b49',
        companyName: '北京长松科技股份有限公司',
        certifyType: 0,
        scale: '1000人以上',
        lon: 116.633729,
        industry: '科学研究和技术服务业',
        regcapCur: '万',
        basicInfo: {
          companyInfoCount: 99,
          businessRiskCount: 6,
          semPromoCount: 1385,
          basicInfoCount: 26,
          newsInfoCount: 0,
          contactCount: 37,
          recruitInfoCount: 73,
          tenderInfoCount: 0,
          patentCount: 264,
        },
        entType: '1000',
        secIndustryShort: ['科技推广和应用服务业'],
        companyLogoUrl: 'https://static-koios.hsmob.com/cio/production_img/5506cb5a137053e25da4bccd9faf32e9.jpg',
        legalPerson: '贾长松',
        businessAddress: '北京市通州区榆景东路5号院46号楼2层',
        hitDescription:
          "网络推广：湖南道同企业管理咨询<font color='#FF1A1A'>有限</font><font color='#FF1A1A'>公司</font>,太原信诺<font color='#FF1A1A'>达</font>企业管理咨询<font color='#FF1A1A'>有限</font><font color='#FF1A1A'>公司</font>,哈尔滨拓展培训<font color='#FF1A1A'>公司</font>,邢台市冰峰企业管理咨询服务<font color='#FF1A1A'>有限</font><font color='#FF1A1A'>公司</font>,咨询<font color='#FF1A1A'>公司</font>排名,河南日浦企业管理咨询<font color='#FF1A1A'>有限</font><font color='#FF1A1A'>公司</font>,深圳总裁班,企业内训讲师,企业文化咨询<font color='#FF1A1A'>公司</font>,四川智生源企业管理咨询<font color='#FF1A1A'>有限</font><font color='#FF1A1A'>公司</font>,江苏善合企业管理咨询服务有限公司",
        companyNameWS:
          "北<font color='#FF1A1A'>京</font>长松科技股份<font color='#FF1A1A'>有</font><font color='#FF1A1A'>限</font><font color='#FF1A1A'>公</font><font color='#FF1A1A'>司</font>",
        lat: 39.94353,
        address: '北京市通州区榆景东路5号院46号楼2层',
        isReceived: 0,
        entBigType: 1,
        tags: [
          { backgroundColor: '#FFEEF2', fontColor: '#F96986', desc: '37个联系方式' },
          { backgroundColor: '#FCEDD8', fontColor: '#FFA72E', desc: '存续' },
          { backgroundColor: '#F1EDF9', fontColor: '#AB73FF', desc: '纳税A级' },
          { backgroundColor: '#F1EDF9', fontColor: '#AB73FF', desc: '民营' },
        ],
        industryMiddle: '其他科技推广服务业',
        esDate: '2017-02-27',
        officialWebsite: 'www.cszx360.com.cn',
        distanceStr: '',
        regcap: 1000,
        entStatus: '1',
        logoDetail: { backgroundColor: '#84CAB0', initials: 'Z', shortCompanyName: '长松科技', fontColor: '#FFFFFF' },
      },
      {
        DPID: 'ccc0c40d4df150ca2af3b688cc7e6c54',
        companyName: '广东鹰航物流有限公司',
        certifyType: 0,
        scale: '100-499人',
        lon: 113.723548,
        industry: '交通运输、仓储和邮政业',
        regcapCur: '万人民币',
        basicInfo: {
          companyInfoCount: 35,
          businessRiskCount: 2,
          semPromoCount: 352,
          basicInfoCount: 180,
          newsInfoCount: 0,
          contactCount: 25,
          recruitInfoCount: 57,
          tenderInfoCount: 0,
          patentCount: 4,
        },
        entType: '1000',
        secIndustryShort: ['多式联运和运输代理业'],
        companyLogoUrl: 'https://static-koios.hsmob.com/cio/production_img/ab38d3950b84582406c62129441a3f2f.png',
        legalPerson: '邱春艳',
        businessAddress: '东莞市南城区宏六路德记物流园F2栋二楼201室',
        hitDescription:
          "历史名称：东莞市鹰航货物运输<font color='#FF1A1A'>有</font><font color='#FF1A1A'>限</font><font color='#FF1A1A'>公</font><font color='#FF1A1A'>司</font>",
        companyNameWS:
          "广东鹰航物流<font color='#FF1A1A'>有</font><font color='#FF1A1A'>限</font><font color='#FF1A1A'>公</font><font color='#FF1A1A'>司</font>",
        lat: 22.980689,
        address: '东莞市南城区宏六路德记物流园F2栋二楼201室',
        isReceived: 0,
        entBigType: 1,
        tags: [
          { backgroundColor: '#FFEEF2', fontColor: '#F96986', desc: '25个联系方式' },
          { backgroundColor: '#FCEDD8', fontColor: '#FFA72E', desc: '存续' },
          { backgroundColor: '#F1EDF9', fontColor: '#AB73FF', desc: '民营' },
        ],
        industryMiddle: '运输代理业',
        esDate: '2009-08-17',
        officialWebsite: 'www.gdyhwl.com',
        distanceStr: '',
        regcap: 2000,
        entStatus: '1',
        logoDetail: { backgroundColor: '#84CAB0', initials: 'Y', shortCompanyName: '鹰航物流', fontColor: '#FFFFFF' },
      },
      {
        DPID: '5ace0cf0ea60b4d193d4f183f0084d53',
        companyName: '广州创沛物流有限公司',
        certifyType: 0,
        scale: '',
        lon: 113.354433,
        industry: '交通运输、仓储和邮政业',
        regcapCur: '万人民币',
        basicInfo: {
          companyInfoCount: 15,
          businessRiskCount: 0,
          semPromoCount: 38,
          basicInfoCount: 9,
          newsInfoCount: 0,
          contactCount: 10,
          recruitInfoCount: 0,
          tenderInfoCount: 0,
          patentCount: 0,
        },
        entType: '1000',
        secIndustryShort: ['道路运输业'],
        companyLogoUrl: 'https://static-koios.hsmob.com/cio/production_img/122dfa501d0716eae3f905c1d219ae7d.jpg',
        legalPerson: '揭学松',
        businessAddress: '广州市白云区太和镇大源中路174号之一广州市泰邦物流信息市场信息号楼207号',
        hitDescription:
          "网络推广：广州市天辅货运,深圳市腾<font color='#FF1A1A'>博达</font>物流,滁州大件物流<font color='#FF1A1A'>公司</font>,深圳至<font color='#FF1A1A'>南京</font>物流<font color='#FF1A1A'>公司</font>,郑州易兴物流<font color='#FF1A1A'>有限</font><font color='#FF1A1A'>公司</font>,肇庆市锦锋物流,佛山市顺德区胜芳物流,广州<font color='#FF1A1A'>南</font>广物流,深圳市焕然一新物流,广州金瀚国际物流,广州到昭通物流专线,上海展天国际物流<font color='#FF1A1A'>有限</font><font color='#FF1A1A'>公司</font>深圳分<font color='#FF1A1A'>公司</font>,广州沪通物流",
        companyNameWS:
          "广州创沛物流<font color='#FF1A1A'>有</font><font color='#FF1A1A'>限</font><font color='#FF1A1A'>公</font><font color='#FF1A1A'>司</font>",
        lat: 23.251933,
        address: '广州市白云区太和镇大源中路174号之一广州市泰邦物流信息市场信息号楼207号',
        isReceived: 0,
        entBigType: 1,
        tags: [
          { backgroundColor: '#FFEEF2', fontColor: '#F96986', desc: '10个联系方式' },
          { backgroundColor: '#FCEDD8', fontColor: '#FFA72E', desc: '存续' },
          { backgroundColor: '#F1EDF9', fontColor: '#AB73FF', desc: '民营' },
        ],
        industryMiddle: '道路货物运输',
        esDate: '2018-04-02',
        officialWebsite: 'www.chuangpei56.com',
        distanceStr: '',
        regcap: 1001,
        entStatus: '1',
        logoDetail: { backgroundColor: '#7DB3D9', initials: 'C', shortCompanyName: '创沛物流', fontColor: '#FFFFFF' },
      },
      {
        DPID: 'd08752c43c633bd8badb4d6b27ca2c4b',
        companyName: '四川阔野建材有限公司',
        certifyType: 0,
        scale: '',
        lon: 104.144043,
        industry: '批发和零售业',
        regcapCur: '万人民币',
        basicInfo: {
          companyInfoCount: 11,
          businessRiskCount: 0,
          semPromoCount: 847,
          basicInfoCount: 4,
          newsInfoCount: 0,
          contactCount: 6,
          recruitInfoCount: 0,
          tenderInfoCount: 0,
          patentCount: 0,
        },
        entType: '1000',
        secIndustryShort: ['批发业'],
        companyLogoUrl: '',
        legalPerson: '田东杰',
        businessAddress: '成都市成华区槐树店路长融街30号5栋2单元1层4号',
        hitDescription:
          "网络推广：天津市天天保温建材<font color='#FF1A1A'>有限</font><font color='#FF1A1A'>公</font>,上海杰新保温材料<font color='#FF1A1A'>有限</font><font color='#FF1A1A'>公司</font>,深圳市璇石特种砂浆,聚氨酯双组份胶,热固性粉末涂料销售,内蒙古彩钢板,西安保温厂家,衡阳市烧结页岩保温砌块,5mm超级隔热材料,博乐市益明砂浆经销部,常州彩钢板,廊坊市华钰保温材料<font color='#FF1A1A'>有限</font><font color='#FF1A1A'>公司</font>,西安防水",
        companyNameWS:
          "四川阔野建材<font color='#FF1A1A'>有</font><font color='#FF1A1A'>限</font><font color='#FF1A1A'>公</font><font color='#FF1A1A'>司</font>",
        lat: 30.655092,
        address: '成都市成华区槐树店路长融街30号5栋2单元1层4号',
        isReceived: 0,
        entBigType: 1,
        tags: [
          { backgroundColor: '#FFEEF2', fontColor: '#F96986', desc: '6个联系方式' },
          { backgroundColor: '#FCEDD8', fontColor: '#FFA72E', desc: '存续' },
          { backgroundColor: '#F1EDF9', fontColor: '#AB73FF', desc: '民营' },
        ],
        industryMiddle: '其他批发业',
        esDate: '2016-03-15',
        officialWebsite: 'www.cdkuoye.com',
        distanceStr: '',
        regcap: 200,
        entStatus: '1',
        logoDetail: { backgroundColor: '#8CA3CD', initials: 'K', shortCompanyName: '阔野建材', fontColor: '#FFFFFF' },
      },
    ],
    pageNum: 1,
    suspectedCount: 0,
    triggerWholeFlag: false,
  },
  errmsg: '',
  globalTicket: '16781-1659334924.395-saas-w1-1423-49897968514',
};
const detailTopResult = {
  errcode: 0,
  data: {
    baseInfo: {
      historyNames: [],
      entName: '博达瑞（南京）科技有限公司',
      insured: '5人',
      DPID: 'd3db408f3d9531169a94b62ed30d17b6',
      certifyType: 0,
      scale: '',
      industry: '制造业',
      regcapCur: '万人民币',
      legalPerson: '田瑞冬',
      annualturnover: '100万以下',
      isSuspected: 0,
      canUpdate: 1,
      address: '南京市江北新区星火路14号长峰大厦1号实验楼3层B02-69室',
      companyLogo: '',
      isReceived: 1,
      entBigType: 1,
      tags: [
        { backgroundColor: '#FFEEF2', fontColor: '#F96986', desc: '2个联系方式' },
        { backgroundColor: '#FCEDD8', fontColor: '#FFA72E', desc: '存续' },
        { backgroundColor: '#F1EDF9', fontColor: '#AB73FF', desc: '民营' },
      ],
      industryMiddle: '汽车零部件及配件制造',
      esDate: '2019-11-11',
      isMonitor: false,
      regcap: 500,
      lastUpdate: '30天前',
      enttypedetail: 1,
      industryShort: '汽车制造业',
      logoDetail: { backgroundColor: '#7DB3D9', initials: 'B', shortCompanyName: '博达瑞', fontColor: '#FFFFFF' },
    },
    basicInfo: {
      companyInfoCount: 10,
      businessRiskCount: 0,
      semPromoCount: 0,
      basicInfoCount: 4,
      newsInfoCount: 0,
      recruitInfoCount: 0,
      tenderInfoCount: 0,
      patentCount: 0,
    },
    menus: [
      {
        isCollection: 0,
        totalCount: 4,
        type: 1,
        detailMenuVos: [
          { isCollection: 0, totalCount: 0, type: 101, detailMenuVos: [], name: '企业简介' },
          { isCollection: 0, totalCount: 0, type: 102, detailMenuVos: [], name: '企业百科' },
          { isCollection: 0, totalCount: 0, type: 110, detailMenuVos: [], name: '创始团队' },
          { isCollection: 1, totalCount: 0, type: 103, detailMenuVos: [], name: '移动APP' },
          { isCollection: 1, totalCount: 0, type: 104, detailMenuVos: [], name: '微信公众号' },
          { isCollection: 1, totalCount: 0, type: 105, detailMenuVos: [], name: '微博' },
          { isCollection: 1, totalCount: 0, type: 106, detailMenuVos: [], name: '旗下网站' },
          { isCollection: 1, totalCount: 0, type: 107, detailMenuVos: [], name: '旗下商品' },
          { isCollection: 1, totalCount: 0, type: 108, detailMenuVos: [], name: '网店信息' },
          { isCollection: 1, totalCount: 0, type: 109, detailMenuVos: [], name: '旗下店铺' },
          { isCollection: 1, totalCount: 4, type: 111, detailMenuVos: [], name: '行政许可' },
          { isCollection: 1, totalCount: 0, type: 112, detailMenuVos: [], name: '进出口' },
          { isCollection: 1, totalCount: 0, type: 113, detailMenuVos: [], name: '参展信息' },
          { isCollection: 1, totalCount: 0, type: 114, detailMenuVos: [], name: '税务信用' },
          { isCollection: 1, totalCount: 0, type: 115, detailMenuVos: [], name: '品牌信息' },
          { isCollection: 1, totalCount: 0, type: 116, detailMenuVos: [], name: '微信小程序' },
          { isCollection: 1, totalCount: 0, type: 117, detailMenuVos: [], name: '注册人员证书' },
        ],
        name: '基本信息',
      },
      {
        isCollection: 0,
        totalCount: 10,
        type: 2,
        detailMenuVos: [
          { isCollection: 0, totalCount: 1, type: 201, detailMenuVos: [], name: '营业执照信息' },
          { isCollection: 1, totalCount: 0, type: 202, detailMenuVos: [], name: '融资历程' },
          { isCollection: 1, totalCount: 1, type: 203, detailMenuVos: [], name: '股东信息' },
          { isCollection: 1, totalCount: 2, type: 209, detailMenuVos: [], name: '主要人员' },
          { isCollection: 0, totalCount: 1, type: 204, detailMenuVos: [], name: '实际受益人' },
          { isCollection: 1, totalCount: 0, type: 205, detailMenuVos: [], name: '对外投资' },
          { isCollection: 1, totalCount: 0, type: 206, detailMenuVos: [], name: '子公司与分支机构' },
          { isCollection: 1, totalCount: 2, type: 207, detailMenuVos: [], name: '工商变更' },
          { isCollection: 1, totalCount: 3, type: 208, detailMenuVos: [], name: '企业年报' },
        ],
        name: '工商详情',
      },
      {
        isCollection: 1,
        totalCount: 0,
        type: 3,
        detailMenuVos: [
          { isCollection: 0, totalCount: 0, type: 301, detailMenuVos: [], name: '招聘统计' },
          { isCollection: 1, totalCount: 0, type: 302, detailMenuVos: [], name: '招聘信息' },
        ],
        name: '招聘信息',
      },
      { isCollection: 1, totalCount: 0, type: 4, detailMenuVos: [], name: '网络推广' },
      {
        isCollection: 1,
        totalCount: 0,
        type: 5,
        detailMenuVos: [
          { isCollection: 1, totalCount: 0, type: 502, detailMenuVos: [], name: '商标信息' },
          { isCollection: 1, totalCount: 0, type: 501, detailMenuVos: [], name: '专利信息' },
          { isCollection: 1, totalCount: 0, type: 503, detailMenuVos: [], name: '资质证书' },
          { isCollection: 1, totalCount: 0, type: 504, detailMenuVos: [], name: '作品著作权' },
          { isCollection: 1, totalCount: 0, type: 505, detailMenuVos: [], name: '软件著作权' },
        ],
        name: '知识产权',
      },
      { isCollection: 1, totalCount: 0, type: 6, detailMenuVos: [], name: '招标投标' },
      { isCollection: 1, totalCount: 0, type: 7, detailMenuVos: [], name: '新闻动态' },
      {
        isCollection: 1,
        totalCount: 0,
        type: 8,
        detailMenuVos: [
          { isCollection: 1, totalCount: 0, type: 801, detailMenuVos: [], name: '抽查信息' },
          { isCollection: 1, totalCount: 0, type: 802, detailMenuVos: [], name: '行政处罚' },
          { isCollection: 1, totalCount: 0, type: 803, detailMenuVos: [], name: '经营异常' },
          { isCollection: 1, totalCount: 0, type: 804, detailMenuVos: [], name: '清算信息' },
          { isCollection: 1, totalCount: 0, type: 805, detailMenuVos: [], name: '简易注销公告信息' },
          { isCollection: 1, totalCount: 0, type: 806, detailMenuVos: [], name: '严重违法失信企业' },
          { isCollection: 1, totalCount: 0, type: 807, detailMenuVos: [], name: '欠税信息' },
          { isCollection: 1, totalCount: 0, type: 808, detailMenuVos: [], name: '税务非正常户' },
          { isCollection: 1, totalCount: 0, type: 809, detailMenuVos: [], name: '税务重大违法' },
          { isCollection: 1, totalCount: 0, type: 810, detailMenuVos: [], name: '产品不合格信息' },
          { isCollection: 1, totalCount: 0, type: 811, detailMenuVos: [], name: '立案公告' },
          { isCollection: 1, totalCount: 0, type: 812, detailMenuVos: [], name: '开庭公告' },
          { isCollection: 1, totalCount: 0, type: 813, detailMenuVos: [], name: '送达公告' },
          { isCollection: 1, totalCount: 0, type: 814, detailMenuVos: [], name: '裁判文书' },
          { isCollection: 1, totalCount: 0, type: 815, detailMenuVos: [], name: '执行信息' },
          { isCollection: 1, totalCount: 0, type: 816, detailMenuVos: [], name: '失信信息' },
          { isCollection: 1, totalCount: 0, type: 817, detailMenuVos: [], name: '司法协助' },
          { isCollection: 1, totalCount: 0, type: 818, detailMenuVos: [], name: '限制高消费' },
          { isCollection: 1, totalCount: 0, type: 819, detailMenuVos: [], name: '终本案件' },
          { isCollection: 1, totalCount: 0, type: 820, detailMenuVos: [], name: '股权出质' },
          { isCollection: 1, totalCount: 0, type: 821, detailMenuVos: [], name: '知识产权出质' },
          { isCollection: 1, totalCount: 0, type: 822, detailMenuVos: [], name: '动产抵押' },
          { isCollection: 0, totalCount: 0, type: 823, detailMenuVos: [], name: '涉诉案件统计分析' },
        ],
        name: '企业风险',
      },
    ],
    contacts: {
      emailNumber: 0,
      landlineNumber: 0,
      cellPhones: [
        {
          isAgency: 1,
          sourceList: [{ sourceId: '2019', url: '', sourceName: '工商企业年报2019' }],
          level: 3,
          dataVersion: 0,
          followType: 0,
          isReceived: 1,
          callAgainFlag: 0,
          remark: '',
          clueId: '',
          reportYear: 2019,
          carrier: '中国电信',
          interestFlag: 1,
          name: '',
          location: '江苏 南京',
          id: 'e0423b62aca655f77e661a9c1785fa5e',
          position: '',
          info: '15380420471',
        },
        {
          isAgency: 0,
          sourceList: [
            { sourceId: '2020', url: '', sourceName: '工商企业年报2020' },
            { sourceId: 0, url: '', sourceName: '工商企业年报2021' },
          ],
          level: 3,
          dataVersion: 0,
          followType: 0,
          isReceived: 1,
          callAgainFlag: 0,
          remark: '',
          clueId: '',
          reportYear: 2020,
          carrier: '中国电信',
          interestFlag: 1,
          name: '',
          location: '江苏 南京',
          id: '046dfbea303cd93be4e9653fcadffc23',
          position: '',
          info: '19951658898',
        },
      ],
      emails: [],
      isShowMask: false,
      landlines: [],
      cellPhoneNumber: 2,
      contactsNumber: 2,
    },
    productTags: [],
  },
  errmsg: '',
  globalTicket: '16785-1659335374.496-saas-w1-1425-49898968341',
};

export type SearchResult = typeof searchResult;
export type DetailTopResult = typeof detailTopResult;
