const a = {
  data: [
    {
      id: '4473724',
      type: 'transcript',
      attributes: {
        publishOn: '2021-12-06T19:02:12-05:00',
        isLockedPro: false,
        commentCount: 0,
        gettyImageUrl: null,
        videoPreviewUrl: null,
        themes: {},
        title: 'GitLab Inc. (GTLB) CEO Sid Sijbrandij On Q3 2022 Results - Earnings Call Transcript',
      },
      relationships: {
        author: { data: { id: '44211', type: 'author' } },
        sentiments: { data: [] },
        primaryTickers: { data: [{ id: '612854', type: 'tag' }] },
        secondaryTickers: { data: [] },
        otherTags: {
          data: [
            { id: '96991', type: 'tag' },
            { id: '17994', type: 'tag' },
            { id: '49', type: 'tag' },
            { id: '586376', type: 'tag' },
            { id: '326', type: 'tag' },
            { id: '18017', type: 'tag' },
          ],
        },
      },
      links: { self: '/article/4473724-gitlab-inc-gtlb-ceo-sid-sijbrandij-on-q3-2022-results-earnings-call-transcript' },
    },
    {
      id: '4473723',
      type: 'transcript',
      attributes: {
        publishOn: '2021-12-06T19:02:04-05:00',
        isLockedPro: false,
        commentCount: 0,
        gettyImageUrl: null,
        videoPreviewUrl: null,
        themes: {},
        title: 'Arista Networks, Inc. (ANET) management presents at Raymond James Virtual Technology Investors Conference (Transcript)',
      },
      relationships: {
        author: { data: { id: '44211', type: 'author' } },
        sentiments: { data: [] },
        primaryTickers: { data: [{ id: '9916', type: 'tag' }] },
        secondaryTickers: { data: [] },
        otherTags: {
          data: [
            { id: '96991', type: 'tag' },
            { id: '17994', type: 'tag' },
            { id: '49', type: 'tag' },
            { id: '586376', type: 'tag' },
            { id: '326', type: 'tag' },
            { id: '18002', type: 'tag' },
          ],
        },
      },
      links: { self: '/article/4473723-arista-networks-inc-anet-management-presents-raymond-james-virtual-technology-investors' },
    },
    {
      id: '4473720',
      type: 'transcript',
      attributes: {
        publishOn: '2021-12-06T18:03:05-05:00',
        isLockedPro: false,
        commentCount: 6,
        gettyImageUrl: null,
        videoPreviewUrl: null,
        themes: {},
        title: 'Marvell Technology, Inc. (MRVL) CEO Matt Murphy Presents at UBS Global TMT Virtual Conference (Transcript)',
      },
      relationships: {
        author: { data: { id: '44211', type: 'author' } },
        sentiments: { data: [] },
        primaryTickers: { data: [{ id: '1308', type: 'tag' }] },
        secondaryTickers: { data: [] },
        otherTags: {
          data: [
            { id: '96991', type: 'tag' },
            { id: '17994', type: 'tag' },
            { id: '49', type: 'tag' },
            { id: '586376', type: 'tag' },
            { id: '326', type: 'tag' },
            { id: '18019', type: 'tag' },
          ],
        },
      },
      links: { self: '/article/4473720-marvell-technology-inc-mrvl-ceo-matt-murphy-presents-ubs-global-tmt-virtual-conference' },
    },
    {
      id: '4473719',
      type: 'transcript',
      attributes: {
        publishOn: '2021-12-06T18:01:04-05:00',
        isLockedPro: false,
        commentCount: 3,
        gettyImageUrl: null,
        videoPreviewUrl: null,
        themes: {},
        title: 'AT&T Inc. (T) Presents at UBS Global TMT Virtual Conference (Transcript)',
      },
      relationships: {
        author: { data: { id: '44211', type: 'author' } },
        sentiments: { data: [] },
        primaryTickers: {
          data: [
            { id: '685', type: 'tag' },
            { id: '585104', type: 'tag' },
            { id: '584543', type: 'tag' },
            { id: '601292', type: 'tag' },
            { id: '601293', type: 'tag' },
          ],
        },
        secondaryTickers: { data: [] },
        otherTags: {
          data: [
            { id: '96991', type: 'tag' },
            { id: '17994', type: 'tag' },
            { id: '49', type: 'tag' },
            { id: '586376', type: 'tag' },
            { id: '326', type: 'tag' },
            { id: '18024', type: 'tag' },
          ],
        },
      },
      links: { self: '/article/4473719-t-inc-t-presents-ubs-global-tmt-virtual-conference-transcript' },
    },
    {
      id: '4473717',
      type: 'transcript',
      attributes: {
        publishOn: '2021-12-06T17:14:03-05:00',
        isLockedPro: false,
        commentCount: 0,
        gettyImageUrl: null,
        videoPreviewUrl: null,
        themes: {},
        title: 'NVIDIA Corporation (NVDA) Management Presents at UBS Global TMT Virtual Conference (Transcript)',
      },
      relationships: {
        author: { data: { id: '44211', type: 'author' } },
        sentiments: { data: [] },
        primaryTickers: { data: [{ id: '1150', type: 'tag' }] },
        secondaryTickers: { data: [] },
        otherTags: {
          data: [
            { id: '96991', type: 'tag' },
            { id: '17994', type: 'tag' },
            { id: '49', type: 'tag' },
            { id: '586376', type: 'tag' },
            { id: '326', type: 'tag' },
            { id: '18020', type: 'tag' },
          ],
        },
      },
      links: { self: '/article/4473717-nvidia-corporation-nvda-management-presents-ubs-global-tmt-virtual-conference-transcript' },
    },
    {
      id: '4473711',
      type: 'transcript',
      attributes: {
        publishOn: '2021-12-06T16:31:08-05:00',
        isLockedPro: false,
        commentCount: 0,
        gettyImageUrl: null,
        videoPreviewUrl: null,
        themes: {},
        title: 'Science Applications International Corporation (SAIC) CEO Nazzic Keene on Q3 2022 Results - Earnings Call Transcript',
      },
      relationships: {
        author: { data: { id: '44211', type: 'author' } },
        sentiments: { data: [] },
        primaryTickers: { data: [{ id: '113132', type: 'tag' }] },
        secondaryTickers: { data: [] },
        otherTags: {
          data: [
            { id: '96991', type: 'tag' },
            { id: '17994', type: 'tag' },
            { id: '49', type: 'tag' },
            { id: '586376', type: 'tag' },
            { id: '326', type: 'tag' },
            { id: '18006', type: 'tag' },
          ],
        },
      },
      links: { self: '/article/4473711-science-applications-international-corporation-saic-ceo-nazzic-keene-on-q3-2022-results' },
    },
    {
      id: '4473709',
      type: 'transcript',
      attributes: {
        publishOn: '2021-12-06T16:24:05-05:00',
        isLockedPro: false,
        commentCount: 0,
        gettyImageUrl: null,
        videoPreviewUrl: null,
        themes: {},
        title: 'Splunk Inc. (SPLK) Management Presents at UBS Global TMT Virtual Brokers Conference (Transcript)',
      },
      relationships: {
        author: { data: { id: '44211', type: 'author' } },
        sentiments: { data: [] },
        primaryTickers: { data: [{ id: '35929', type: 'tag' }] },
        secondaryTickers: { data: [] },
        otherTags: {
          data: [
            { id: '96991', type: 'tag' },
            { id: '17994', type: 'tag' },
            { id: '49', type: 'tag' },
            { id: '586376', type: 'tag' },
            { id: '326', type: 'tag' },
            { id: '17995', type: 'tag' },
          ],
        },
      },
      links: { self: '/article/4473709-splunk-inc-splk-management-presents-ubs-global-tmt-virtual-brokers-conference-transcript' },
    },
    {
      id: '4473704',
      type: 'transcript',
      attributes: {
        publishOn: '2021-12-06T15:54:05-05:00',
        isLockedPro: false,
        commentCount: 0,
        gettyImageUrl: null,
        videoPreviewUrl: null,
        themes: {},
        title: "Booking Holdings' (BKNG) CEO Glenn Fogel Presents at UBS Global TMT Virtual Conference 2021 (Transcript)",
      },
      relationships: {
        author: { data: { id: '44211', type: 'author' } },
        sentiments: { data: [] },
        primaryTickers: { data: [{ id: '581', type: 'tag' }] },
        secondaryTickers: { data: [] },
        otherTags: {
          data: [
            { id: '96991', type: 'tag' },
            { id: '17933', type: 'tag' },
            { id: '49', type: 'tag' },
            { id: '586376', type: 'tag' },
            { id: '326', type: 'tag' },
            { id: '17960', type: 'tag' },
          ],
        },
      },
      links: { self: '/article/4473704-booking-holdings-bkng-ceo-glenn-fogel-presents-ubs-global-tmt-virtual-conference-2021' },
    },
    {
      id: '4473703',
      type: 'transcript',
      attributes: {
        publishOn: '2021-12-06T15:48:11-05:00',
        isLockedPro: false,
        commentCount: 0,
        gettyImageUrl: null,
        videoPreviewUrl: null,
        themes: {},
        title: 'CrowdStrike Holdings, Inc. (CRWD) Management Presents at UBS Global TMT Virtual Conference (Transcript)',
      },
      relationships: {
        author: { data: { id: '44211', type: 'author' } },
        sentiments: { data: [] },
        primaryTickers: { data: [{ id: '122301', type: 'tag' }] },
        secondaryTickers: { data: [] },
        otherTags: {
          data: [
            { id: '96991', type: 'tag' },
            { id: '17994', type: 'tag' },
            { id: '49', type: 'tag' },
            { id: '586376', type: 'tag' },
            { id: '326', type: 'tag' },
            { id: '18009', type: 'tag' },
          ],
        },
      },
      links: { self: '/article/4473703-crowdstrike-holdings-inc-crwd-management-presents-ubs-global-tmt-virtual-conference' },
    },
    {
      id: '4473702',
      type: 'transcript',
      attributes: {
        publishOn: '2021-12-06T15:48:03-05:00',
        isLockedPro: false,
        commentCount: 0,
        gettyImageUrl: null,
        videoPreviewUrl: null,
        themes: {},
        title: 'Cisco Systems, Inc. (CSCO) Presents at Raymond James 2021 Technology Investors Conference (Transcript)',
      },
      relationships: {
        author: { data: { id: '44211', type: 'author' } },
        sentiments: { data: [] },
        primaryTickers: { data: [{ id: '670', type: 'tag' }] },
        secondaryTickers: { data: [] },
        otherTags: {
          data: [
            { id: '96991', type: 'tag' },
            { id: '17994', type: 'tag' },
            { id: '49', type: 'tag' },
            { id: '586376', type: 'tag' },
            { id: '326', type: 'tag' },
            { id: '18012', type: 'tag' },
          ],
        },
      },
      links: { self: '/article/4473702-cisco-systems-inc-csco-presents-raymond-james-2021-technology-investors-conference-transcript' },
    },
    {
      id: '4473699',
      type: 'transcript',
      attributes: {
        publishOn: '2021-12-06T15:33:04-05:00',
        isLockedPro: false,
        commentCount: 0,
        gettyImageUrl: null,
        videoPreviewUrl: null,
        themes: {},
        title: 'Fastly Inc. (FSLY) CEO Joshua Bixby Presents at Raymond James 2021 Technology Investors Conference (Transcript)',
      },
      relationships: {
        author: { data: { id: '44211', type: 'author' } },
        sentiments: { data: [] },
        primaryTickers: { data: [{ id: '598944', type: 'tag' }] },
        secondaryTickers: { data: [] },
        otherTags: {
          data: [
            { id: '96991', type: 'tag' },
            { id: '17994', type: 'tag' },
            { id: '49', type: 'tag' },
            { id: '586376', type: 'tag' },
            { id: '326', type: 'tag' },
            { id: '18009', type: 'tag' },
          ],
        },
      },
      links: { self: '/article/4473699-fastly-inc-fsly-ceo-joshua-bixby-presents-raymond-james-2021-technology-investors-conference' },
    },
    {
      id: '4473694',
      type: 'transcript',
      attributes: {
        publishOn: '2021-12-06T15:04:06-05:00',
        isLockedPro: false,
        commentCount: 0,
        gettyImageUrl: null,
        videoPreviewUrl: null,
        themes: {},
        title: 'Western Digital Corporation (WDC) CEO David Goeckeler Presents at UBS Global TMT Virtual Conference (Transcript)',
      },
      relationships: {
        author: { data: { id: '44211', type: 'author' } },
        sentiments: { data: [] },
        primaryTickers: { data: [{ id: '1064', type: 'tag' }] },
        secondaryTickers: { data: [] },
        otherTags: {
          data: [
            { id: '96991', type: 'tag' },
            { id: '17994', type: 'tag' },
            { id: '49', type: 'tag' },
            { id: '586376', type: 'tag' },
            { id: '326', type: 'tag' },
            { id: '18000', type: 'tag' },
          ],
        },
      },
      links: { self: '/article/4473694-western-digital-corporation-wdc-ceo-david-goeckeler-presents-ubs-global-tmt-virtual' },
    },
    {
      id: '4473692',
      type: 'transcript',
      attributes: {
        publishOn: '2021-12-06T14:53:04-05:00',
        isLockedPro: false,
        commentCount: 0,
        gettyImageUrl: null,
        videoPreviewUrl: null,
        themes: {},
        title: 'Cisco Systems, Inc. (CSCO) Management Presents at UBS Global TMT Virtual Brokers Conference (Transcript)',
      },
      relationships: {
        author: { data: { id: '44211', type: 'author' } },
        sentiments: { data: [] },
        primaryTickers: { data: [{ id: '670', type: 'tag' }] },
        secondaryTickers: { data: [] },
        otherTags: {
          data: [
            { id: '96991', type: 'tag' },
            { id: '17994', type: 'tag' },
            { id: '49', type: 'tag' },
            { id: '586376', type: 'tag' },
            { id: '326', type: 'tag' },
            { id: '18012', type: 'tag' },
          ],
        },
      },
      links: { self: '/article/4473692-cisco-systems-inc-csco-management-presents-ubs-global-tmt-virtual-brokers-conference' },
    },
    {
      id: '4473689',
      type: 'transcript',
      attributes: {
        publishOn: '2021-12-06T14:23:04-05:00',
        isLockedPro: false,
        commentCount: 0,
        gettyImageUrl: null,
        videoPreviewUrl: null,
        themes: {},
        title: 'American Tower Corporation. (AMT) Presents at UBS Global TMT Virtual Conference (Transcript)',
      },
      relationships: {
        author: { data: { id: '44211', type: 'author' } },
        sentiments: { data: [] },
        primaryTickers: { data: [{ id: '1916', type: 'tag' }] },
        secondaryTickers: { data: [] },
        otherTags: {
          data: [
            { id: '96991', type: 'tag' },
            { id: '17994', type: 'tag' },
            { id: '49', type: 'tag' },
            { id: '586376', type: 'tag' },
            { id: '326', type: 'tag' },
            { id: '18001', type: 'tag' },
          ],
        },
      },
      links: { self: '/article/4473689-american-tower-corporation-amt-presents-ubs-global-tmt-virtual-conference-transcript' },
    },
    {
      id: '4473677',
      type: 'transcript',
      attributes: {
        publishOn: '2021-12-06T13:56:05-05:00',
        isLockedPro: false,
        commentCount: 1,
        gettyImageUrl: null,
        videoPreviewUrl: null,
        themes: {},
        title: 'Verizon Communications Inc. (VZ) CEO Hans Vestberg Presents at 2021 UBS Global TMT Conference (Transcript)',
      },
      relationships: {
        author: { data: { id: '44211', type: 'author' } },
        sentiments: { data: [] },
        primaryTickers: { data: [{ id: '693', type: 'tag' }] },
        secondaryTickers: { data: [] },
        otherTags: {
          data: [
            { id: '96991', type: 'tag' },
            { id: '17994', type: 'tag' },
            { id: '49', type: 'tag' },
            { id: '586376', type: 'tag' },
            { id: '326', type: 'tag' },
            { id: '18024', type: 'tag' },
          ],
        },
      },
      links: { self: '/article/4473677-verizon-communications-inc-vz-ceo-hans-vestberg-presents-2021-ubs-global-tmt-conference' },
    },
    {
      id: '4473666',
      type: 'transcript',
      attributes: {
        publishOn: '2021-12-06T13:17:03-05:00',
        isLockedPro: false,
        commentCount: 1,
        gettyImageUrl: null,
        videoPreviewUrl: null,
        themes: {},
        title: 'VMware, Inc. (VMW) Management Presents at 2021 UBS Global TMT Virtual Conference (Transcript)',
      },
      relationships: {
        author: { data: { id: '44211', type: 'author' } },
        sentiments: { data: [] },
        primaryTickers: { data: [{ id: '8350', type: 'tag' }] },
        secondaryTickers: { data: [] },
        otherTags: {
          data: [
            { id: '96991', type: 'tag' },
            { id: '17994', type: 'tag' },
            { id: '49', type: 'tag' },
            { id: '586376', type: 'tag' },
            { id: '326', type: 'tag' },
            { id: '18023', type: 'tag' },
          ],
        },
      },
      links: { self: '/article/4473666-vmware-inc-vmw-management-presents-2021-ubs-global-tmt-virtual-conference-transcript' },
    },
    {
      id: '4473645',
      type: 'transcript',
      attributes: {
        publishOn: '2021-12-06T11:59:04-05:00',
        isLockedPro: false,
        commentCount: 0,
        gettyImageUrl: null,
        videoPreviewUrl: null,
        themes: {},
        title: 'Dell Technologies Inc. (DELL) Presents At Raymond James 2021 Technology Investors Conference (Transcript)',
      },
      relationships: {
        author: { data: { id: '44211', type: 'author' } },
        sentiments: { data: [] },
        primaryTickers: { data: [{ id: '569700', type: 'tag' }] },
        secondaryTickers: { data: [] },
        otherTags: {
          data: [
            { id: '96991', type: 'tag' },
            { id: '17994', type: 'tag' },
            { id: '49', type: 'tag' },
            { id: '586376', type: 'tag' },
            { id: '326', type: 'tag' },
          ],
        },
      },
      links: { self: '/article/4473645-dell-technologies-inc-dell-presents-raymond-james-2021-technology-investors-conference' },
    },
    {
      id: '4473613',
      type: 'transcript',
      attributes: {
        publishOn: '2021-12-06T10:47:02-05:00',
        isLockedPro: false,
        commentCount: 0,
        gettyImageUrl: null,
        videoPreviewUrl: null,
        themes: {},
        title: "Superior Energy Services, Inc.'s (SPNX) Q3 2021 Results - Earnings Call Transcript",
      },
      relationships: {
        author: { data: { id: '44211', type: 'author' } },
        sentiments: { data: [] },
        primaryTickers: {
          data: [
            { id: '1902', type: 'tag' },
            { id: '611827', type: 'tag' },
          ],
        },
        secondaryTickers: { data: [] },
        otherTags: {
          data: [
            { id: '96991', type: 'tag' },
            { id: '17810', type: 'tag' },
            { id: '49', type: 'tag' },
            { id: '586376', type: 'tag' },
            { id: '326', type: 'tag' },
            { id: '17821', type: 'tag' },
          ],
        },
      },
      links: { self: '/article/4473613-superior-energy-services-inc-s-spnx-q3-2021-results-earnings-call-transcript' },
    },
    {
      id: '4473602',
      type: 'transcript',
      attributes: {
        publishOn: '2021-12-06T09:22:07-05:00',
        isLockedPro: false,
        commentCount: 0,
        gettyImageUrl: null,
        videoPreviewUrl: null,
        themes: {},
        title: 'Victrex plc (VTXPF) CEO Jakob Sigurdsson on Q4 2021 Results - Earnings Call Transcript',
      },
      relationships: {
        author: { data: { id: '44211', type: 'author' } },
        sentiments: { data: [] },
        primaryTickers: { data: [{ id: '33742', type: 'tag' }] },
        secondaryTickers: { data: [] },
        otherTags: {
          data: [
            { id: '96991', type: 'tag' },
            { id: '17913', type: 'tag' },
            { id: '49', type: 'tag' },
            { id: '586376', type: 'tag' },
            { id: '18107', type: 'tag' },
            { id: '17813', type: 'tag' },
          ],
        },
      },
      links: { self: '/article/4473602-victrex-plc-vtxpf-ceo-jakob-sigurdsson-on-q4-2021-results-earnings-call-transcript' },
    },
    {
      id: '4473339',
      type: 'transcript',
      attributes: {
        publishOn: '2021-12-03T17:17:03-05:00',
        isLockedPro: false,
        commentCount: 0,
        gettyImageUrl: null,
        videoPreviewUrl: null,
        themes: {},
        title: 'AGM Group Holdings Inc. (AGMH) Co-CEO Wenjie Tang on Q3 2021 Results - Earnings Call Transcript',
      },
      relationships: {
        author: { data: { id: '44211', type: 'author' } },
        sentiments: { data: [] },
        primaryTickers: { data: [{ id: '581924', type: 'tag' }] },
        secondaryTickers: { data: [] },
        otherTags: {
          data: [
            { id: '96991', type: 'tag' },
            { id: '17994', type: 'tag' },
            { id: '49', type: 'tag' },
            { id: '586376', type: 'tag' },
            { id: '18059', type: 'tag' },
          ],
        },
      },
      links: { self: '/article/4473339-agm-group-holdings-inc-agmh-co-ceo-wenjie-tang-on-q3-2021-results-earnings-call-transcript' },
    },
  ],
  included: [
    {
      id: '44211',
      type: 'author',
      attributes: {
        company: null,
        slug: 'sa-transcripts',
        userId: 101639,
        tagId: 96991,
        image: {
          small: 'https://static3.seekingalpha.com/images/users_profile/000/101/639/small_pic.png',
          medium: 'https://static3.seekingalpha.com/images/users_profile/000/101/639/medium_pic.png',
          big: 'https://static3.seekingalpha.com/images/users_profile/000/101/639/big_pic.png',
          extra_large: 'https://static3.seekingalpha.com/images/users_profile/000/101/639/extra_large_pic.png',
        },
        nick: 'SA Transcripts',
        bio: "Seeking Alpha's transcripts team is responsible for the development of all of our transcript-related projects. We currently publish thousands of quarterly earnings calls per quarter on our site and are continuing to grow and expand our coverage. The purpose of this profile is to allow us to share with our readers new transcript-related developments. Thanks, SA Transcripts Team",
        memberSince: 2007,
        contributorSince: 2013,
        followersCount: 128520,
      },
      relationships: { user: { data: { id: '101639', type: 'user' } } },
      links: { self: '/author/sa-transcripts', profileUrl: '/author/sa-transcripts', site: null, linkedinUrl: null, twitterUrl: null },
    },
    { id: '612854', type: 'tag', attributes: { slug: 'gtlb', name: 'GTLB' }, links: { self: '/symbol/GTLB' } },
    { id: '9916', type: 'tag', attributes: { slug: 'anet', name: 'ANET' }, links: { self: '/symbol/ANET' } },
    { id: '1308', type: 'tag', attributes: { slug: 'mrvl', name: 'MRVL' }, links: { self: '/symbol/MRVL' } },
    { id: '685', type: 'tag', attributes: { slug: 't', name: 'T' }, links: { self: '/symbol/T' } },
    { id: '585104', type: 'tag', attributes: { slug: 'tbb', name: 'TBB' }, links: { self: '/symbol/TBB' } },
    { id: '584543', type: 'tag', attributes: { slug: 'tbc', name: 'TBC' }, links: { self: '/symbol/TBC' } },
    { id: '601292', type: 'tag', attributes: { slug: 't.pa', name: 'T.PA' }, links: { self: '/symbol/T.PA' } },
    { id: '601293', type: 'tag', attributes: { slug: 't.pc', name: 'T.PC' }, links: { self: '/symbol/T.PC' } },
    { id: '1150', type: 'tag', attributes: { slug: 'nvda', name: 'NVDA' }, links: { self: '/symbol/NVDA' } },
    { id: '113132', type: 'tag', attributes: { slug: 'saic', name: 'SAIC' }, links: { self: '/symbol/SAIC' } },
    { id: '35929', type: 'tag', attributes: { slug: 'splk', name: 'SPLK' }, links: { self: '/symbol/SPLK' } },
    { id: '581', type: 'tag', attributes: { slug: 'bkng', name: 'BKNG' }, links: { self: '/symbol/BKNG' } },
    { id: '122301', type: 'tag', attributes: { slug: 'crwd', name: 'CRWD' }, links: { self: '/symbol/CRWD' } },
    { id: '670', type: 'tag', attributes: { slug: 'csco', name: 'CSCO' }, links: { self: '/symbol/CSCO' } },
    { id: '598944', type: 'tag', attributes: { slug: 'fsly', name: 'FSLY' }, links: { self: '/symbol/FSLY' } },
    { id: '1064', type: 'tag', attributes: { slug: 'wdc', name: 'WDC' }, links: { self: '/symbol/WDC' } },
    { id: '1916', type: 'tag', attributes: { slug: 'amt', name: 'AMT' }, links: { self: '/symbol/AMT' } },
    { id: '693', type: 'tag', attributes: { slug: 'vz', name: 'VZ' }, links: { self: '/symbol/VZ' } },
    { id: '8350', type: 'tag', attributes: { slug: 'vmw', name: 'VMW' }, links: { self: '/symbol/VMW' } },
    { id: '569700', type: 'tag', attributes: { slug: 'dell', name: 'DELL' }, links: { self: '/symbol/DELL' } },
    { id: '1902', type: 'tag', attributes: { slug: 'spnx', name: 'SPNX' }, links: { self: '/symbol/SPNX' } },
    { id: '611827', type: 'tag', attributes: { slug: 'spnr', name: 'SPNR' }, links: { self: '/symbol/SPNR' } },
    { id: '33742', type: 'tag', attributes: { slug: 'vtxpf', name: 'VTXPF' }, links: { self: '/symbol/VTXPF' } },
    { id: '581924', type: 'tag', attributes: { slug: 'agmh', name: 'AGMH' }, links: { self: '/symbol/AGMH' } },
  ],
  meta: {
    page: {
      title: 'Earnings Call Transcripts',
      description: 'Complete transcripts of earnings calls, including the Audio and slideshow presentations.',
      listTitle: 'Earnings Transcripts',
      listDescription: null,
      proStatus: 0,
      size: 20,
      totalPages: 9408,
      total: 188158,
      minmaxPublishOn: { min: 1638569823, max: 1638835332 },
    },
    mone: { params: { pu: '' } },
    introText: null,
    h1Title: null,
  },
};
export type Data = typeof a
