const a = {
  msg: 'success',
  code: 0,
  data: {
    totalItem: 11509,
    data: [
      {
        sellerStatus: 99,
        sellerStatusDesc: '待招募',
        sellerId: 12420367,
        shopName: '京新家纺专营店',
        companyName: '襄阳京新科技有限公司',
        created: 1659079027000,
        shopScoreRank: '4.5',
        categortyNames:
          '布料,坐垫,挂毯/壁毯,三件套,四件套,多件套,羽绒/羽毛被,蚕丝被,羊毛/驼毛被,床帘,纤维被,棉花被,乳胶被,乳胶枕,记忆枕,花草枕,纤维枕,羽绒枕,蚕丝枕,蚊帐,草席/藤席,竹席,冰丝席,粗布凉席,其它凉席,床单/床笠,毛毯,床垫/床褥,被套,枕巾枕套,毛巾,浴巾,毛巾礼盒套装,地毯,地垫,抱枕靠垫,桌布/罩件,沙发垫套,窗帘/窗纱,特殊商品,一次性洗脸巾',
        purchaserPin: '京新01',
        createdDesc: '2022-07-29',
      },
      {
        sellerStatus: 99,
        sellerStatusDesc: '待招募',
        sellerId: 1000377906,
        shopName: '木中央京东自营旗舰店',
        companyName: '北京京东世纪信息技术有限公司',
        created: 1659078850000,
        shopScoreRank: '0.0',
        categortyNames: '红木电视柜,顶箱柜,衣柜,红木餐桌,红木衣柜,红木沙发,沙发床,红木茶桌',
        purchaserPin: '中若家具厂',
        createdDesc: '2022-07-29',
      },
      {
        sellerStatus: 99,
        sellerStatusDesc: '待招募',
        sellerId: 10723543,
        shopName: '途默汽车用品专营店',
        companyName: '广州途默贸易有限公司',
        created: 1659071317000,
        shopScoreRank: '4.5',
        categortyNames:
          '车载香水,内饰贴,防滑贴,仪表台防晒垫,密封条,车门拉手装饰,挡泥板,防撞胶条,车衣,车载支架,轮毂喷膜,洗车泥,摆件,洗车水桶,洗车海绵,洗车手套,车用砂纸,后视镜/圆镜,雨眉,车身装饰件,镀膜,防雾剂/驱水剂,喷漆,车用掸子,车身装饰条,保险杠,排挡/手刹套,汽车钥匙扣/包,汽车炭包,扶手箱,车载烟灰缸,临时停车牌,镀晶,汽车防滑垫,防踢垫,洗车毛巾,遮阳挡/雪挡,方向盘套,车蜡,玻璃水,清洁剂,其它洗车工具,汽车改色膜,打蜡机,挂件,其它功能小件,补漆笔',
        purchaserPin: '途默汽车用品专营店',
        createdDesc: '2022-07-29',
      },
      {
        sellerStatus: 99,
        sellerStatusDesc: '待招募',
        sellerId: 755535,
        shopName: '四叶草家居专营店',
        companyName: '六安四叶草网络科技有限公司',
        created: 1659066781000,
        shopScoreRank: '4.0',
        categortyNames:
          '抽纸,卷纸,手帕纸,湿巾,厨房纸巾,湿厕纸,多功能置物架,其它纸品/湿巾,铲勺,一次性清洁用品,垃圾桶,拖把,脸盆,抹布/百洁布,手套/鞋套/围裙,手动切片机,清洁刷具,锅盖,其它清洁工具,冰棒模具/冰格,清洁用具配件,普通洗衣液,切菜器/刨丝器,洗衣粉,洗衣皂,炒锅,柔顺剂,厨用取碗/盘夹,平底锅/煎锅,除菌剂,打蛋工具,高压锅,其它衣物清洁,蒸锅,洗洁精,汤锅,油污清洁剂,其它厨房小工具,奶锅,除湿干燥剂,锅具套装,洁厕剂,砂锅,空调清洁剂,水壶,消毒液,地板清洁剂,菜刀,其它清洁用品,剪刀,驱蚊用品,刀具套装,灭鼠/杀虫剂,砧板,皮具护理品,护理工具,保鲜盒,烘焙/烧烤,调料器皿,饭盒/提锅,塑料杯,玻璃杯,陶瓷/马克杯,保温杯,保温壶,酒杯/酒具,餐具套装,茶具/咖啡具,碗,筷子,一次性用品,雨伞雨具,浴室用品,缝纫机,洗晒/熨烫,净化除味,鞋架,储物/收纳用品,墙面搁架,层架/置物架,台灯,荧光灯源,壁灯,落地灯,筒灯/射灯,应急灯,室外/庭院灯,LED灯源,吸顶灯,氛围照明,吊灯,帘艺隔断,墙贴/装饰贴,钟饰,花瓶花艺,香薰蜡烛,创意家居,运动水壶,果盘/果篮,火锅,厨房置物架,粘毛器,厨房DIY/小工具,水桶,杯具套装,瓜果刀/刨,多功能刀,缝纫/针织材料,扫把簸箕,玻璃清洁器,家用除尘掸,焖烧杯,太阳能灯,特殊商品,特殊商品,特殊商品,水具/酒具配件,整套茶具,茶杯,厨房秤,茶壶,茶盘茶托,气球,茶叶罐,串灯,茶具配件,特殊商品,红包,茶宠摆件,礼花礼炮,三件套,喜糖盒/袋,其他,四件套,对联,特殊商品,多件套,灯笼,特殊商品,羽绒/羽毛被,贺卡,特殊商品,蚕丝被,应援灯牌,特殊商品,羊毛/驼毛被,横幅/条幅,特殊商品,纤维被,圣诞装饰品,相框/照片墙,特殊商品,棉花被,万圣装饰品,装饰字画,乳胶枕,其它婚庆节庆用品,节庆饰品,记忆枕,手工饰品,花草枕,装饰摆件,纤维枕,保暖防护,羽绒枕,蚕丝枕,蚊帐,牛皮席,草席/藤席,竹席,冰丝席,粗布凉席,其它凉席,床单/床笠,毛毯,床垫/床褥,被套,枕巾枕套,电热毯,毛巾,浴巾,毛巾礼盒套装,地毯,地垫,抱枕靠垫,桌布/罩件,沙发垫套,窗帘/窗纱,收纳袋/包,收纳柜,收纳箱,防尘罩,收纳架/篮,收纳盒,分隔收纳,杀菌灯',
        purchaserPin: 'clover13053027827',
        createdDesc: '2022-07-29',
      },
      {
        sellerStatus: 99,
        sellerStatusDesc: '待招募',
        sellerId: 12415421,
        shopName: '汤乐鲜旗舰店',
        companyName: '珠海市金湾区觉来商贸有限公司',
        created: 1659065716000,
        shopScoreRank: '2.5',
        categortyNames: '方便菜',
        purchaserPin: 'juelaifood4',
        createdDesc: '2022-07-29',
      },
      {
        sellerStatus: 99,
        sellerStatusDesc: '待招募',
        sellerId: 11877816,
        shopName: '富美拉居家日用旗舰店',
        companyName: '深圳市叁壹汇通科技有限公司',
        created: 1659065607000,
        shopScoreRank: '4.0',
        categortyNames:
          '钱包,男士钱包,登山包,旅行包,行李箱,钥匙包,卡包/零钱包,双肩包,单肩/斜挎包,钥匙包,腰包/胸包,婚庆节庆,熏香,壁饰,挂毯/壁毯,颈椎枕,雨伞雨具,浴室用品,缝纫机,洗晒/熨烫,净化除味,特殊商品,特殊商品,特殊商品,特殊商品,特殊商品,布料,坐垫,手拿包,单肩包,女士双肩包,手提包,斜挎包,男士手包,气球,串灯,书包,红包,礼花礼炮,三件套,喜糖盒/袋,四件套,对联,多件套,灯笼,羽绒/羽毛被,贺卡,蚕丝被,应援灯牌,羊毛/驼毛被,横幅/条幅,床帘,纤维被,圣诞装饰品,相框/照片墙,棉花被,乳胶被,万圣装饰品,装饰字画,乳胶枕,其它婚庆节庆用品,节庆饰品,记忆枕,手工饰品,花草枕,电脑包,装饰摆件,纤维枕,休闲运动包,保暖防护,羽绒枕,蚕丝枕,旅行配件,蚊帐,牛皮席,草席/藤席,竹席,冰丝席,粗布凉席,其它凉席,床单/床笠,毛毯,床垫/床褥,被套,枕巾枕套,毛巾,浴巾,商务公文包,毛巾礼盒套装,地毯,地垫,抱枕靠垫,皮带礼盒,桌布/罩件,女士皮带,沙发垫套,窗帘/窗纱,特殊商品,帘艺隔断,墙贴/装饰贴,钟饰,花瓶花艺,香薰蜡烛,创意家居,箱包配件,手机包,证件包,化妆包,收纳袋/包,收纳柜,收纳箱,防尘罩,收纳架/篮,缝纫/针织材料,收纳盒,卡包名片夹,拉杆包,上门除醛,分隔收纳,男士皮带',
        purchaserPin: 'sanyihuitong003',
        createdDesc: '2022-07-29',
      },
      {
        sellerStatus: 99,
        sellerStatusDesc: '待招募',
        sellerId: 12388679,
        shopName: '联想铭科世纪专卖店',
        companyName: '北京铭科世纪科技有限公司',
        created: 1659065255000,
        shopScoreRank: '4.5',
        categortyNames: '投影机',
        purchaserPin: '联想铭科专卖店',
        createdDesc: '2022-07-29',
      },
      {
        sellerStatus: 99,
        sellerStatusDesc: '待招募',
        sellerId: 12543873,
        shopName: '钦芯达智能家居专营店',
        companyName: '莆田市钦芯达贸易有限公司',
        created: 1659063904000,
        shopScoreRank: '0.0',
        categortyNames:
          '特殊商品,格栅/面板灯,植物生长灯,生鲜灯,磁吸轨道灯,太阳能灯,工矿灯,路灯,台灯,荧光灯源,壁灯,落地灯,筒灯/射灯,室外/庭院灯,应急灯,LED灯源,吸顶灯,氛围照明,吊灯,麻将灯,吊扇灯,卤钨灯源,其它光源,镜前灯,杀菌灯,灯具配件,其它照明',
        purchaserPin: '钦芯达',
        createdDesc: '2022-07-29',
      },
      {
        sellerStatus: 99,
        sellerStatusDesc: '待招募',
        sellerId: 12560680,
        shopName: '伦家物语饮料小店',
        companyName: '沁阳市伦家物语商贸网店',
        created: 1659063311000,
        shopScoreRank: '0.0',
        categortyNames: '休闲零食',
        purchaserPin: '伦家858',
        createdDesc: '2022-07-29',
      },
      {
        sellerStatus: 99,
        sellerStatusDesc: '待招募',
        sellerId: 11160145,
        shopName: '京乾电脑专营店',
        companyName: '莆田市京乾贸易有限公司',
        created: 1659062968000,
        shopScoreRank: '3.0',
        categortyNames: '显示器,电视配件,特殊商品,平板电视,机箱',
        purchaserPin: '京乾电脑专营店',
        createdDesc: '2022-07-29',
      },
    ],
    pageNo: 2,
    pageSize: 10,
  },
  uuid: '4c33af184fa297b01440aaadea98bd22',
};

const b = {
  msg: 'success',
  code: 0,
  data: {
    shopName: '京新家纺专营店',
    userType: 1,
    companyName: '襄阳京新科技有限公司',
    companyAddr: '',
    contactMan: '张宁',
    contactMail: '503904154@qq.com',
    contactPhone: '18771535553',
    contactTel: '',
    purchaserPin: '京新01',
    shopifyMark: 0,
  },
  invoiceAbility: '支持开具普票',
  uuid: '8c2e55b531ec353325bd0225f39cb26d',
};
export type TableData = typeof a;
export type Info = typeof b;
